import { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "tiere",
    name: "Tiere",
    emoji: "🐶",
    from: "#f7b733",
    to: "#fc4a1a",
    words: [
      { de: "der Hund", en: "dog", es: "el perro", emoji: "🐶", lvl: 1 },
      { de: "die Katze", en: "cat", es: "el gato", emoji: "🐱", lvl: 1 },
      { de: "die Maus", en: "mouse", es: "el ratón", emoji: "🐭", lvl: 1 },
      { de: "das Pferd", en: "horse", es: "el caballo", emoji: "🐴", lvl: 1 },
      { de: "die Kuh", en: "cow", es: "la vaca", emoji: "🐮", lvl: 1 },
      { de: "das Schwein", en: "pig", es: "el cerdo", emoji: "🐷", lvl: 1 },
      { de: "das Schaf", en: "sheep", es: "la oveja", emoji: "🐑", lvl: 2 },
      { de: "die Ziege", en: "goat", es: "la cabra", emoji: "🐐", lvl: 2 },
      { de: "das Huhn", en: "chicken", es: "la gallina", emoji: "🐔", lvl: 1 },
      { de: "die Ente", en: "duck", es: "el pato", emoji: "🦆", lvl: 1 },
      { de: "der Vogel", en: "bird", es: "el pájaro", emoji: "🐦", lvl: 1 },
      { de: "der Fisch", en: "fish", es: "el pez", emoji: "🐟", lvl: 1 },
      { de: "der Löwe", en: "lion", es: "el león", emoji: "🦁", lvl: 1 },
      { de: "der Tiger", en: "tiger", es: "el tigre", emoji: "🐯", lvl: 1 },
      { de: "der Elefant", en: "elephant", es: "el elefante", emoji: "🐘", lvl: 1 },
      { de: "der Affe", en: "monkey", es: "el mono", emoji: "🐵", lvl: 1 },
      { de: "der Bär", en: "bear", es: "el oso", emoji: "🐻", lvl: 1 },
      { de: "der Wolf", en: "wolf", es: "el lobo", emoji: "🐺", lvl: 2 },
      { de: "der Fuchs", en: "fox", es: "el zorro", emoji: "🦊", lvl: 2 },
      { de: "der Hase", en: "rabbit", es: "el conejo", emoji: "🐰", lvl: 1 },
      { de: "der Frosch", en: "frog", es: "la rana", emoji: "🐸", lvl: 1 },
      { de: "die Schlange", en: "snake", es: "la serpiente", emoji: "🐍", lvl: 2 },
      { de: "die Spinne", en: "spider", es: "la araña", emoji: "🕷️", lvl: 2 },
      { de: "die Biene", en: "bee", es: "la abeja", emoji: "🐝", lvl: 2 },
      { de: "der Schmetterling", en: "butterfly", es: "la mariposa", emoji: "🦋", lvl: 2 },
      { de: "die Ameise", en: "ant", es: "la hormiga", emoji: "🐜", lvl: 3 },
      { de: "die Giraffe", en: "giraffe", es: "la jirafa", emoji: "🦒", lvl: 1 },
      { de: "das Zebra", en: "zebra", es: "la cebra", emoji: "🦓", lvl: 2 },
      { de: "das Känguru", en: "kangaroo", es: "el canguro", emoji: "🦘", lvl: 2 },
      { de: "der Pinguin", en: "penguin", es: "el pingüino", emoji: "🐧", lvl: 1 },
      { de: "die Eule", en: "owl", es: "el búho", emoji: "🦉", lvl: 2 },
      { de: "der Delfin", en: "dolphin", es: "el delfín", emoji: "🐬", lvl: 2 },
      { de: "der Wal", en: "whale", es: "la ballena", emoji: "🐳", lvl: 2 },
      { de: "der Hai", en: "shark", es: "el tiburón", emoji: "🦈", lvl: 2 },
      { de: "das Krokodil", en: "crocodile", es: "el cocodrilo", emoji: "🐊", lvl: 2 },
      { de: "die Schildkröte", en: "turtle", es: "la tortuga", emoji: "🐢", lvl: 2 },
      { de: "der Igel", en: "hedgehog", es: "el erizo", emoji: "🦔", lvl: 3 },
      { de: "das Eichhörnchen", en: "squirrel", es: "la ardilla", emoji: "🐿️", lvl: 3 },
      { de: "der Adler", en: "eagle", es: "el águila", emoji: "🦅", lvl: 3 },
      { de: "der Krebs", en: "crab", es: "el cangrejo", emoji: "🦀", lvl: 3 },
    ],
  },
  {
    id: "essen",
    name: "Essen & Trinken",
    emoji: "🍎",
    from: "#ff758c",
    to: "#ff7eb3",
    words: [
      { de: "der Apfel", en: "apple", es: "la manzana", emoji: "🍎", lvl: 1 },
      { de: "die Banane", en: "banana", es: "el plátano", emoji: "🍌", lvl: 1 },
      { de: "die Orange", en: "orange", es: "la naranja", emoji: "🍊", lvl: 1 },
      { de: "die Erdbeere", en: "strawberry", es: "la fresa", emoji: "🍓", lvl: 1 },
      { de: "die Zitrone", en: "lemon", es: "el limón", emoji: "🍋", lvl: 2 },
      { de: "die Kirsche", en: "cherry", es: "la cereza", emoji: "🍒", lvl: 2 },
      { de: "die Traube", en: "grape", es: "la uva", emoji: "🍇", lvl: 2 },
      { de: "die Wassermelone", en: "watermelon", es: "la sandía", emoji: "🍉", lvl: 2 },
      { de: "die Birne", en: "pear", es: "la pera", emoji: "🍐", lvl: 2 },
      { de: "der Pfirsich", en: "peach", es: "el melocotón", emoji: "🍑", lvl: 3 },
      { de: "die Ananas", en: "pineapple", es: "la piña", emoji: "🍍", lvl: 2 },
      { de: "die Tomate", en: "tomato", es: "el tomate", emoji: "🍅", lvl: 1 },
      { de: "die Kartoffel", en: "potato", es: "la patata", emoji: "🥔", lvl: 1 },
      { de: "die Karotte", en: "carrot", es: "la zanahoria", emoji: "🥕", lvl: 1 },
      { de: "die Zwiebel", en: "onion", es: "la cebolla", emoji: "🧅", lvl: 3 },
      { de: "der Salat", en: "salad", es: "la ensalada", emoji: "🥗", lvl: 2 },
      { de: "das Brot", en: "bread", es: "el pan", emoji: "🍞", lvl: 1 },
      { de: "der Käse", en: "cheese", es: "el queso", emoji: "🧀", lvl: 1 },
      { de: "das Ei", en: "egg", es: "el huevo", emoji: "🥚", lvl: 1 },
      { de: "die Milch", en: "milk", es: "la leche", emoji: "🥛", lvl: 1 },
      { de: "die Butter", en: "butter", es: "la mantequilla", emoji: "🧈", lvl: 2 },
      { de: "der Reis", en: "rice", es: "el arroz", emoji: "🍚", lvl: 2 },
      { de: "die Nudeln", en: "pasta", es: "la pasta", emoji: "🍝", lvl: 1 },
      { de: "die Pizza", en: "pizza", es: "la pizza", emoji: "🍕", lvl: 1 },
      { de: "die Suppe", en: "soup", es: "la sopa", emoji: "🍲", lvl: 2 },
      { de: "das Fleisch", en: "meat", es: "la carne", emoji: "🥩", lvl: 2 },
      { de: "das Hähnchen", en: "chicken", es: "el pollo", emoji: "🍗", lvl: 2 },
      { de: "der Schinken", en: "ham", es: "el jamón", emoji: "🥓", lvl: 3 },
      { de: "der Honig", en: "honey", es: "la miel", emoji: "🍯", lvl: 3 },
      { de: "der Zucker", en: "sugar", es: "el azúcar", emoji: "🥄", lvl: 3 },
      { de: "das Salz", en: "salt", es: "la sal", emoji: "🧂", lvl: 2 },
      { de: "der Kuchen", en: "cake", es: "el pastel", emoji: "🍰", lvl: 1 },
      { de: "der Keks", en: "cookie", es: "la galleta", emoji: "🍪", lvl: 1 },
      { de: "die Schokolade", en: "chocolate", es: "el chocolate", emoji: "🍫", lvl: 1 },
      { de: "das Eis", en: "ice cream", es: "el helado", emoji: "🍦", lvl: 1 },
      { de: "das Bonbon", en: "candy", es: "el caramelo", emoji: "🍬", lvl: 2 },
      { de: "das Wasser", en: "water", es: "el agua", emoji: "💧", lvl: 1 },
      { de: "der Saft", en: "juice", es: "el zumo", emoji: "🧃", lvl: 1 },
      { de: "der Tee", en: "tea", es: "el té", emoji: "🍵", lvl: 2 },
      { de: "der Kaffee", en: "coffee", es: "el café", emoji: "☕", lvl: 1 },
    ],
  },
  {
    id: "familie",
    name: "Familie & Menschen",
    emoji: "👨‍👩‍👧",
    from: "#a18cd1",
    to: "#fbc2eb",
    words: [
      { de: "die Mutter", en: "mother", es: "la madre", emoji: "👩", lvl: 1 },
      { de: "der Vater", en: "father", es: "el padre", emoji: "👨", lvl: 1 },
      { de: "die Eltern", en: "parents", es: "los padres", emoji: "👫", lvl: 2 },
      { de: "die Schwester", en: "sister", es: "la hermana", emoji: "👧", lvl: 1 },
      { de: "der Bruder", en: "brother", es: "el hermano", emoji: "👦", lvl: 1 },
      { de: "die Oma", en: "grandma", es: "la abuela", emoji: "👵", lvl: 1 },
      { de: "der Opa", en: "grandpa", es: "el abuelo", emoji: "👴", lvl: 1 },
      { de: "die Tante", en: "aunt", es: "la tía", emoji: "💁‍♀️", lvl: 2 },
      { de: "der Onkel", en: "uncle", es: "el tío", emoji: "🙋‍♂️", lvl: 2 },
      { de: "der Cousin", en: "cousin", es: "el primo", emoji: "🧑", lvl: 3 },
      { de: "das Baby", en: "baby", es: "el bebé", emoji: "👶", lvl: 1 },
      { de: "das Kind", en: "child", es: "el niño", emoji: "🧒", lvl: 1 },
      { de: "der Junge", en: "boy", es: "el chico", emoji: "👦", lvl: 1 },
      { de: "das Mädchen", en: "girl", es: "la chica", emoji: "👧", lvl: 1 },
      { de: "der Mann", en: "man", es: "el hombre", emoji: "🧔", lvl: 1 },
      { de: "die Frau", en: "woman", es: "la mujer", emoji: "👱‍♀️", lvl: 1 },
      { de: "der Sohn", en: "son", es: "el hijo", emoji: "👨‍👦", lvl: 2 },
      { de: "die Tochter", en: "daughter", es: "la hija", emoji: "👩‍👧", lvl: 2 },
      { de: "die Familie", en: "family", es: "la familia", emoji: "👨‍👩‍👧‍👦", lvl: 1 },
      { de: "der Freund", en: "friend", es: "el amigo", emoji: "🤝", lvl: 1 },
      { de: "die Freundin", en: "friend (girl)", es: "la amiga", emoji: "👭", lvl: 2 },
      { de: "der Nachbar", en: "neighbour", es: "el vecino", emoji: "🏘️", lvl: 3 },
      { de: "der Lehrer", en: "teacher", es: "el profesor", emoji: "🧑‍🏫", lvl: 1 },
      { de: "der Arzt", en: "doctor", es: "el médico", emoji: "🧑‍⚕️", lvl: 2 },
      { de: "der Polizist", en: "police officer", es: "el policía", emoji: "👮", lvl: 2 },
      { de: "der Feuerwehrmann", en: "firefighter", es: "el bombero", emoji: "🧑‍🚒", lvl: 2 },
      { de: "der Koch", en: "cook", es: "el cocinero", emoji: "🧑‍🍳", lvl: 2 },
      { de: "der Bauer", en: "farmer", es: "el agricultor", emoji: "🧑‍🌾", lvl: 3 },
      { de: "die Zwillinge", en: "twins", es: "los gemelos", emoji: "👯", lvl: 3 },
      { de: "der Ehemann", en: "husband", es: "el marido", emoji: "🤵", lvl: 3 },
      { de: "die Ehefrau", en: "wife", es: "la esposa", emoji: "👰", lvl: 3 },
      { de: "die Person", en: "person", es: "la persona", emoji: "🧍", lvl: 2 },
      { de: "die Leute", en: "people", es: "la gente", emoji: "👥", lvl: 2 },
      { de: "der Name", en: "name", es: "el nombre", emoji: "📛", lvl: 2 },
      { de: "der Geburtstag", en: "birthday", es: "el cumpleaños", emoji: "🎂", lvl: 1 },
      { de: "der Gast", en: "guest", es: "el invitado", emoji: "🛎️", lvl: 3 },
    ],
  },
  {
    id: "farben",
    name: "Farben & Formen",
    emoji: "🎨",
    from: "#ff6ec4",
    to: "#7873f5",
    words: [
      { de: "rot", en: "red", es: "rojo", emoji: "🔴", lvl: 1 },
      { de: "blau", en: "blue", es: "azul", emoji: "🔵", lvl: 1 },
      { de: "grün", en: "green", es: "verde", emoji: "🟢", lvl: 1 },
      { de: "gelb", en: "yellow", es: "amarillo", emoji: "🟡", lvl: 1 },
      { de: "orange", en: "orange", es: "naranja", emoji: "🟠", lvl: 1 },
      { de: "lila", en: "purple", es: "morado", emoji: "🟣", lvl: 1 },
      { de: "rosa", en: "pink", es: "rosa", emoji: "🌸", lvl: 1 },
      { de: "braun", en: "brown", es: "marrón", emoji: "🟤", lvl: 1 },
      { de: "schwarz", en: "black", es: "negro", emoji: "⚫", lvl: 1 },
      { de: "weiß", en: "white", es: "blanco", emoji: "⚪", lvl: 1 },
      { de: "grau", en: "grey", es: "gris", emoji: "🩶", lvl: 2 },
      { de: "golden", en: "golden", es: "dorado", emoji: "🥇", lvl: 2 },
      { de: "silbern", en: "silver", es: "plateado", emoji: "🥈", lvl: 2 },
      { de: "hell", en: "light", es: "claro", emoji: "💡", lvl: 2 },
      { de: "dunkel", en: "dark", es: "oscuro", emoji: "🌑", lvl: 2 },
      { de: "bunt", en: "colourful", es: "de colores", emoji: "🌈", lvl: 2 },
      { de: "der Kreis", en: "circle", es: "el círculo", emoji: "⭕", lvl: 2 },
      { de: "das Quadrat", en: "square", es: "el cuadrado", emoji: "🟥", lvl: 2 },
      { de: "das Dreieck", en: "triangle", es: "el triángulo", emoji: "🔺", lvl: 2 },
      { de: "das Rechteck", en: "rectangle", es: "el rectángulo", emoji: "🟦", lvl: 3 },
      { de: "der Stern", en: "star", es: "la estrella", emoji: "⭐", lvl: 1 },
      { de: "das Herz", en: "heart", es: "el corazón", emoji: "❤️", lvl: 1 },
      { de: "der Punkt", en: "dot", es: "el punto", emoji: "🔘", lvl: 3 },
      { de: "die Linie", en: "line", es: "la línea", emoji: "〰️", lvl: 3 },
      { de: "der Pfeil", en: "arrow", es: "la flecha", emoji: "➡️", lvl: 2 },
      { de: "die Form", en: "shape", es: "la forma", emoji: "🔷", lvl: 3 },
      { de: "der Würfel", en: "cube", es: "el cubo", emoji: "🎲", lvl: 3 },
      { de: "das Muster", en: "pattern", es: "el patrón", emoji: "🧩", lvl: 3 },
    ],
  },
  {
    id: "zahlen",
    name: "Zahlen",
    emoji: "🔢",
    from: "#4facfe",
    to: "#00f2fe",
    words: [
      { de: "null", en: "zero", es: "cero", emoji: "0️⃣", lvl: 1 },
      { de: "eins", en: "one", es: "uno", emoji: "1️⃣", lvl: 1 },
      { de: "zwei", en: "two", es: "dos", emoji: "2️⃣", lvl: 1 },
      { de: "drei", en: "three", es: "tres", emoji: "3️⃣", lvl: 1 },
      { de: "vier", en: "four", es: "cuatro", emoji: "4️⃣", lvl: 1 },
      { de: "fünf", en: "five", es: "cinco", emoji: "5️⃣", lvl: 1 },
      { de: "sechs", en: "six", es: "seis", emoji: "6️⃣", lvl: 1 },
      { de: "sieben", en: "seven", es: "siete", emoji: "7️⃣", lvl: 1 },
      { de: "acht", en: "eight", es: "ocho", emoji: "8️⃣", lvl: 1 },
      { de: "neun", en: "nine", es: "nueve", emoji: "9️⃣", lvl: 1 },
      { de: "zehn", en: "ten", es: "diez", emoji: "🔟", lvl: 1 },
      { de: "elf", en: "eleven", es: "once", emoji: "1️⃣1️⃣", lvl: 2 },
      { de: "zwölf", en: "twelve", es: "doce", emoji: "1️⃣2️⃣", lvl: 2 },
      { de: "dreizehn", en: "thirteen", es: "trece", emoji: "1️⃣3️⃣", lvl: 2 },
      { de: "vierzehn", en: "fourteen", es: "catorce", emoji: "1️⃣4️⃣", lvl: 2 },
      { de: "fünfzehn", en: "fifteen", es: "quince", emoji: "1️⃣5️⃣", lvl: 2 },
      { de: "sechzehn", en: "sixteen", es: "dieciséis", emoji: "1️⃣6️⃣", lvl: 2 },
      { de: "siebzehn", en: "seventeen", es: "diecisiete", emoji: "1️⃣7️⃣", lvl: 2 },
      { de: "achtzehn", en: "eighteen", es: "dieciocho", emoji: "1️⃣8️⃣", lvl: 2 },
      { de: "neunzehn", en: "nineteen", es: "diecinueve", emoji: "1️⃣9️⃣", lvl: 2 },
      { de: "zwanzig", en: "twenty", es: "veinte", emoji: "2️⃣0️⃣", lvl: 2 },
      { de: "dreißig", en: "thirty", es: "treinta", emoji: "3️⃣0️⃣", lvl: 3 },
      { de: "vierzig", en: "forty", es: "cuarenta", emoji: "4️⃣0️⃣", lvl: 3 },
      { de: "fünfzig", en: "fifty", es: "cincuenta", emoji: "5️⃣0️⃣", lvl: 3 },
      { de: "sechzig", en: "sixty", es: "sesenta", emoji: "6️⃣0️⃣", lvl: 3 },
      { de: "siebzig", en: "seventy", es: "setenta", emoji: "7️⃣0️⃣", lvl: 3 },
      { de: "achtzig", en: "eighty", es: "ochenta", emoji: "8️⃣0️⃣", lvl: 3 },
      { de: "neunzig", en: "ninety", es: "noventa", emoji: "9️⃣0️⃣", lvl: 3 },
      { de: "hundert", en: "one hundred", es: "cien", emoji: "💯", lvl: 2 },
      { de: "tausend", en: "one thousand", es: "mil", emoji: "🔢", lvl: 3 },
      { de: "die Hälfte", en: "half", es: "la mitad", emoji: "➗", lvl: 3 },
    ],
  },
  {
    id: "koerper",
    name: "Körper",
    emoji: "💪",
    from: "#fa709a",
    to: "#fee140",
    words: [
      { de: "der Kopf", en: "head", es: "la cabeza", emoji: "👤", lvl: 1 },
      { de: "das Haar", en: "hair", es: "el pelo", emoji: "💇", lvl: 1 },
      { de: "das Gesicht", en: "face", es: "la cara", emoji: "🙂", lvl: 1 },
      { de: "das Auge", en: "eye", es: "el ojo", emoji: "👁️", lvl: 1 },
      { de: "das Ohr", en: "ear", es: "la oreja", emoji: "👂", lvl: 1 },
      { de: "die Nase", en: "nose", es: "la nariz", emoji: "👃", lvl: 1 },
      { de: "der Mund", en: "mouth", es: "la boca", emoji: "👄", lvl: 1 },
      { de: "der Zahn", en: "tooth", es: "el diente", emoji: "🦷", lvl: 1 },
      { de: "die Zunge", en: "tongue", es: "la lengua", emoji: "👅", lvl: 2 },
      { de: "die Lippe", en: "lip", es: "el labio", emoji: "💋", lvl: 3 },
      { de: "der Hals", en: "neck", es: "el cuello", emoji: "🦒", lvl: 2 },
      { de: "die Schulter", en: "shoulder", es: "el hombro", emoji: "🤷", lvl: 2 },
      { de: "der Arm", en: "arm", es: "el brazo", emoji: "💪", lvl: 1 },
      { de: "der Ellbogen", en: "elbow", es: "el codo", emoji: "🦾", lvl: 3 },
      { de: "die Hand", en: "hand", es: "la mano", emoji: "✋", lvl: 1 },
      { de: "der Finger", en: "finger", es: "el dedo", emoji: "☝️", lvl: 1 },
      { de: "der Daumen", en: "thumb", es: "el pulgar", emoji: "👍", lvl: 2 },
      { de: "der Bauch", en: "belly", es: "la barriga", emoji: "🤰", lvl: 2 },
      { de: "der Rücken", en: "back", es: "la espalda", emoji: "🔙", lvl: 2 },
      { de: "das Bein", en: "leg", es: "la pierna", emoji: "🦵", lvl: 1 },
      { de: "das Knie", en: "knee", es: "la rodilla", emoji: "🧎", lvl: 2 },
      { de: "der Fuß", en: "foot", es: "el pie", emoji: "🦶", lvl: 1 },
      { de: "der Zeh", en: "toe", es: "el dedo del pie", emoji: "🩴", lvl: 3 },
      { de: "das Blut", en: "blood", es: "la sangre", emoji: "🩸", lvl: 3 },
      { de: "der Knochen", en: "bone", es: "el hueso", emoji: "🦴", lvl: 2 },
      { de: "die Haut", en: "skin", es: "la piel", emoji: "🧴", lvl: 3 },
      { de: "das Gehirn", en: "brain", es: "el cerebro", emoji: "🧠", lvl: 2 },
      { de: "der Muskel", en: "muscle", es: "el músculo", emoji: "🏋️", lvl: 3 },
      { de: "die Augenbraue", en: "eyebrow", es: "la ceja", emoji: "🤨", lvl: 3 },
      { de: "die Wange", en: "cheek", es: "la mejilla", emoji: "☺️", lvl: 3 },
      { de: "das Kinn", en: "chin", es: "la barbilla", emoji: "😶", lvl: 3 },
      { de: "der Fingernagel", en: "fingernail", es: "la uña", emoji: "💅", lvl: 3 },
      { de: "der Bart", en: "beard", es: "la barba", emoji: "🧔", lvl: 2 },
      { de: "der Körper", en: "body", es: "el cuerpo", emoji: "🧍", lvl: 1 },
      { de: "das Skelett", en: "skeleton", es: "el esqueleto", emoji: "💀", lvl: 2 },
    ],
  },
  {
    id: "kleidung",
    name: "Kleidung",
    emoji: "👕",
    from: "#5ee7df",
    to: "#b490ca",
    words: [
      { de: "das T-Shirt", en: "t-shirt", es: "la camiseta", emoji: "👕", lvl: 1 },
      { de: "die Hose", en: "trousers", es: "los pantalones", emoji: "👖", lvl: 1 },
      { de: "das Kleid", en: "dress", es: "el vestido", emoji: "👗", lvl: 1 },
      { de: "der Rock", en: "skirt", es: "la falda", emoji: "💃", lvl: 2 },
      { de: "der Pullover", en: "sweater", es: "el jersey", emoji: "🧶", lvl: 2 },
      { de: "die Jacke", en: "jacket", es: "la chaqueta", emoji: "🧥", lvl: 1 },
      { de: "der Mantel", en: "coat", es: "el abrigo", emoji: "🥼", lvl: 2 },
      { de: "der Schuh", en: "shoe", es: "el zapato", emoji: "👟", lvl: 1 },
      { de: "der Stiefel", en: "boot", es: "la bota", emoji: "👢", lvl: 2 },
      { de: "die Socke", en: "sock", es: "el calcetín", emoji: "🧦", lvl: 1 },
      { de: "der Hut", en: "hat", es: "el sombrero", emoji: "🎩", lvl: 1 },
      { de: "die Mütze", en: "cap", es: "la gorra", emoji: "🧢", lvl: 1 },
      { de: "der Schal", en: "scarf", es: "la bufanda", emoji: "🧣", lvl: 2 },
      { de: "der Handschuh", en: "glove", es: "el guante", emoji: "🧤", lvl: 2 },
      { de: "der Gürtel", en: "belt", es: "el cinturón", emoji: "➰", lvl: 3 },
      { de: "die Krawatte", en: "tie", es: "la corbata", emoji: "👔", lvl: 3 },
      { de: "der Anzug", en: "suit", es: "el traje", emoji: "🤵", lvl: 3 },
      { de: "der Schlafanzug", en: "pyjamas", es: "el pijama", emoji: "🛌", lvl: 2 },
      { de: "der Badeanzug", en: "swimsuit", es: "el bañador", emoji: "🩱", lvl: 2 },
      { de: "die Unterhose", en: "underpants", es: "los calzoncillos", emoji: "🩲", lvl: 2 },
      { de: "die Brille", en: "glasses", es: "las gafas", emoji: "👓", lvl: 1 },
      { de: "die Sonnenbrille", en: "sunglasses", es: "las gafas de sol", emoji: "🕶️", lvl: 2 },
      { de: "die Uhr", en: "watch", es: "el reloj", emoji: "⌚", lvl: 1 },
      { de: "der Ring", en: "ring", es: "el anillo", emoji: "💍", lvl: 2 },
      { de: "die Halskette", en: "necklace", es: "el collar", emoji: "📿", lvl: 3 },
      { de: "die Tasche", en: "bag", es: "el bolso", emoji: "👜", lvl: 2 },
      { de: "der Rucksack", en: "backpack", es: "la mochila", emoji: "🎒", lvl: 1 },
      { de: "der Regenschirm", en: "umbrella", es: "el paraguas", emoji: "☂️", lvl: 2 },
      { de: "der Knopf", en: "button", es: "el botón", emoji: "🔘", lvl: 3 },
      { de: "der Reißverschluss", en: "zip", es: "la cremallera", emoji: "🤐", lvl: 3 },
      { de: "die Sandale", en: "sandal", es: "la sandalia", emoji: "🩴", lvl: 2 },
      { de: "die Shorts", en: "shorts", es: "los pantalones cortos", emoji: "🩳", lvl: 2 },
    ],
  },
  {
    id: "schule",
    name: "Schule",
    emoji: "🏫",
    from: "#667eea",
    to: "#764ba2",
    words: [
      { de: "die Schule", en: "school", es: "la escuela", emoji: "🏫", lvl: 1 },
      { de: "die Klasse", en: "class", es: "la clase", emoji: "👩‍🏫", lvl: 2 },
      { de: "der Schüler", en: "pupil", es: "el alumno", emoji: "🧑‍🎓", lvl: 2 },
      { de: "das Buch", en: "book", es: "el libro", emoji: "📖", lvl: 1 },
      { de: "das Heft", en: "notebook", es: "el cuaderno", emoji: "📓", lvl: 1 },
      { de: "der Stift", en: "pen", es: "el bolígrafo", emoji: "🖊️", lvl: 1 },
      { de: "der Bleistift", en: "pencil", es: "el lápiz", emoji: "✏️", lvl: 1 },
      { de: "der Radiergummi", en: "rubber", es: "la goma", emoji: "🧽", lvl: 2 },
      { de: "das Lineal", en: "ruler", es: "la regla", emoji: "📏", lvl: 2 },
      { de: "die Schere", en: "scissors", es: "las tijeras", emoji: "✂️", lvl: 1 },
      { de: "der Kleber", en: "glue", es: "el pegamento", emoji: "🩹", lvl: 2 },
      { de: "die Tafel", en: "blackboard", es: "la pizarra", emoji: "⬛", lvl: 2 },
      { de: "die Kreide", en: "chalk", es: "la tiza", emoji: "🖍️", lvl: 3 },
      { de: "der Stuhl", en: "chair", es: "la silla", emoji: "🪑", lvl: 1 },
      { de: "der Tisch", en: "table", es: "la mesa", emoji: "🍽️", lvl: 1 },
      { de: "die Pause", en: "break", es: "el recreo", emoji: "⏰", lvl: 1 },
      { de: "die Hausaufgaben", en: "homework", es: "los deberes", emoji: "📝", lvl: 1 },
      { de: "die Prüfung", en: "exam", es: "el examen", emoji: "📄", lvl: 2 },
      { de: "die Frage", en: "question", es: "la pregunta", emoji: "❓", lvl: 1 },
      { de: "die Antwort", en: "answer", es: "la respuesta", emoji: "✅", lvl: 1 },
      { de: "lesen", en: "to read", es: "leer", emoji: "📚", lvl: 1 },
      { de: "schreiben", en: "to write", es: "escribir", emoji: "✍️", lvl: 1 },
      { de: "rechnen", en: "to do maths", es: "calcular", emoji: "🧮", lvl: 2 },
      { de: "malen", en: "to paint", es: "pintar", emoji: "🎨", lvl: 1 },
      { de: "lernen", en: "to learn", es: "aprender", emoji: "🎓", lvl: 1 },
      { de: "sprechen", en: "to speak", es: "hablar", emoji: "🗣️", lvl: 1 },
      { de: "hören", en: "to listen", es: "escuchar", emoji: "🎧", lvl: 1 },
      { de: "verstehen", en: "to understand", es: "entender", emoji: "💡", lvl: 2 },
      { de: "Mathe", en: "maths", es: "las matemáticas", emoji: "➕", lvl: 1 },
      { de: "die Musik", en: "music", es: "la música", emoji: "🎵", lvl: 1 },
      { de: "die Kunst", en: "art", es: "el arte", emoji: "🖼️", lvl: 2 },
      { de: "der Computer", en: "computer", es: "el ordenador", emoji: "💻", lvl: 1 },
      { de: "das Papier", en: "paper", es: "el papel", emoji: "📃", lvl: 1 },
      { de: "das Wort", en: "word", es: "la palabra", emoji: "🔤", lvl: 1 },
      { de: "der Satz", en: "sentence", es: "la frase", emoji: "💬", lvl: 2 },
      { de: "die Sprache", en: "language", es: "el idioma", emoji: "🌐", lvl: 2 },
      { de: "Englisch", en: "English", es: "el inglés", emoji: "🇬🇧", lvl: 1 },
      { de: "Spanisch", en: "Spanish", es: "el español", emoji: "🇪🇸", lvl: 1 },
      { de: "Deutsch", en: "German", es: "el alemán", emoji: "🇩🇪", lvl: 1 },
      { de: "die Ferien", en: "holidays", es: "las vacaciones", emoji: "🏖️", lvl: 1 },
    ],
  },
  {
    id: "natur",
    name: "Natur & Wetter",
    emoji: "🌳",
    from: "#0ba360",
    to: "#3cba92",
    words: [
      { de: "die Sonne", en: "sun", es: "el sol", emoji: "☀️", lvl: 1 },
      { de: "der Mond", en: "moon", es: "la luna", emoji: "🌙", lvl: 1 },
      { de: "der Himmel", en: "sky", es: "el cielo", emoji: "🌌", lvl: 1 },
      { de: "die Wolke", en: "cloud", es: "la nube", emoji: "☁️", lvl: 1 },
      { de: "der Regen", en: "rain", es: "la lluvia", emoji: "🌧️", lvl: 1 },
      { de: "der Schnee", en: "snow", es: "la nieve", emoji: "❄️", lvl: 1 },
      { de: "der Wind", en: "wind", es: "el viento", emoji: "💨", lvl: 1 },
      { de: "der Sturm", en: "storm", es: "la tormenta", emoji: "⛈️", lvl: 2 },
      { de: "der Blitz", en: "lightning", es: "el rayo", emoji: "⚡", lvl: 2 },
      { de: "der Regenbogen", en: "rainbow", es: "el arco iris", emoji: "🌈", lvl: 1 },
      { de: "der Nebel", en: "fog", es: "la niebla", emoji: "🌫️", lvl: 3 },
      { de: "das Eis", en: "ice", es: "el hielo", emoji: "🧊", lvl: 2 },
      { de: "der Baum", en: "tree", es: "el árbol", emoji: "🌳", lvl: 1 },
      { de: "die Blume", en: "flower", es: "la flor", emoji: "🌼", lvl: 1 },
      { de: "das Gras", en: "grass", es: "la hierba", emoji: "🌱", lvl: 1 },
      { de: "das Blatt", en: "leaf", es: "la hoja", emoji: "🍃", lvl: 2 },
      { de: "der Wald", en: "forest", es: "el bosque", emoji: "🌲", lvl: 1 },
      { de: "der Berg", en: "mountain", es: "la montaña", emoji: "⛰️", lvl: 1 },
      { de: "der Fluss", en: "river", es: "el río", emoji: "🏞️", lvl: 2 },
      { de: "der See", en: "lake", es: "el lago", emoji: "🛶", lvl: 2 },
      { de: "das Meer", en: "sea", es: "el mar", emoji: "🌊", lvl: 1 },
      { de: "der Strand", en: "beach", es: "la playa", emoji: "🏖️", lvl: 1 },
      { de: "die Insel", en: "island", es: "la isla", emoji: "🏝️", lvl: 2 },
      { de: "die Wüste", en: "desert", es: "el desierto", emoji: "🏜️", lvl: 3 },
      { de: "der Stein", en: "stone", es: "la piedra", emoji: "🪨", lvl: 2 },
      { de: "der Sand", en: "sand", es: "la arena", emoji: "⏳", lvl: 2 },
      { de: "das Feuer", en: "fire", es: "el fuego", emoji: "🔥", lvl: 1 },
      { de: "die Erde", en: "earth", es: "la tierra", emoji: "🌍", lvl: 1 },
      { de: "die Natur", en: "nature", es: "la naturaleza", emoji: "🌿", lvl: 2 },
      { de: "das Wetter", en: "weather", es: "el tiempo", emoji: "🌦️", lvl: 1 },
      { de: "heiß", en: "hot", es: "caliente", emoji: "🥵", lvl: 1 },
      { de: "kalt", en: "cold", es: "frío", emoji: "🥶", lvl: 1 },
      { de: "der Frühling", en: "spring", es: "la primavera", emoji: "🌷", lvl: 2 },
      { de: "der Sommer", en: "summer", es: "el verano", emoji: "😎", lvl: 1 },
      { de: "der Herbst", en: "autumn", es: "el otoño", emoji: "🍂", lvl: 2 },
      { de: "der Winter", en: "winter", es: "el invierno", emoji: "⛄", lvl: 1 },
      { de: "die Pflanze", en: "plant", es: "la planta", emoji: "🪴", lvl: 2 },
    ],
  },
  {
    id: "fahrzeuge",
    name: "Fahrzeuge & Verkehr",
    emoji: "🚗",
    from: "#f83600",
    to: "#f9d423",
    words: [
      { de: "das Auto", en: "car", es: "el coche", emoji: "🚗", lvl: 1 },
      { de: "der Bus", en: "bus", es: "el autobús", emoji: "🚌", lvl: 1 },
      { de: "der Zug", en: "train", es: "el tren", emoji: "🚆", lvl: 1 },
      { de: "das Fahrrad", en: "bicycle", es: "la bicicleta", emoji: "🚲", lvl: 1 },
      { de: "das Motorrad", en: "motorbike", es: "la moto", emoji: "🏍️", lvl: 2 },
      { de: "der Lastwagen", en: "lorry", es: "el camión", emoji: "🚚", lvl: 2 },
      { de: "das Flugzeug", en: "plane", es: "el avión", emoji: "✈️", lvl: 1 },
      { de: "der Hubschrauber", en: "helicopter", es: "el helicóptero", emoji: "🚁", lvl: 2 },
      { de: "das Schiff", en: "ship", es: "el barco", emoji: "🚢", lvl: 1 },
      { de: "das Boot", en: "boat", es: "el bote", emoji: "⛵", lvl: 1 },
      { de: "die U-Bahn", en: "underground", es: "el metro", emoji: "🚇", lvl: 2 },
      { de: "die Straßenbahn", en: "tram", es: "el tranvía", emoji: "🚊", lvl: 3 },
      { de: "das Taxi", en: "taxi", es: "el taxi", emoji: "🚕", lvl: 1 },
      { de: "der Krankenwagen", en: "ambulance", es: "la ambulancia", emoji: "🚑", lvl: 2 },
      { de: "das Feuerwehrauto", en: "fire engine", es: "el camión de bomberos", emoji: "🚒", lvl: 1 },
      { de: "das Polizeiauto", en: "police car", es: "el coche de policía", emoji: "🚓", lvl: 1 },
      { de: "der Traktor", en: "tractor", es: "el tractor", emoji: "🚜", lvl: 1 },
      { de: "die Rakete", en: "rocket", es: "el cohete", emoji: "🚀", lvl: 1 },
      { de: "der Heißluftballon", en: "hot-air balloon", es: "el globo", emoji: "🎈", lvl: 2 },
      { de: "der Roller", en: "scooter", es: "el patinete", emoji: "🛴", lvl: 1 },
      { de: "das Skateboard", en: "skateboard", es: "el monopatín", emoji: "🛹", lvl: 2 },
      { de: "die Straße", en: "street", es: "la calle", emoji: "🛣️", lvl: 1 },
      { de: "die Ampel", en: "traffic lights", es: "el semáforo", emoji: "🚦", lvl: 1 },
      { de: "die Brücke", en: "bridge", es: "el puente", emoji: "🌉", lvl: 2 },
      { de: "die Tankstelle", en: "petrol station", es: "la gasolinera", emoji: "⛽", lvl: 3 },
      { de: "der Bahnhof", en: "station", es: "la estación", emoji: "🚉", lvl: 2 },
      { de: "der Flughafen", en: "airport", es: "el aeropuerto", emoji: "🛫", lvl: 2 },
      { de: "der Hafen", en: "port", es: "el puerto", emoji: "⚓", lvl: 3 },
      { de: "das Ticket", en: "ticket", es: "el billete", emoji: "🎫", lvl: 2 },
      { de: "das Rad", en: "wheel", es: "la rueda", emoji: "🛞", lvl: 2 },
      { de: "fahren", en: "to drive", es: "conducir", emoji: "🚙", lvl: 1 },
      { de: "fliegen", en: "to fly", es: "volar", emoji: "🛩️", lvl: 1 },
      { de: "schnell", en: "fast", es: "rápido", emoji: "🏎️", lvl: 1 },
      { de: "langsam", en: "slow", es: "lento", emoji: "🐌", lvl: 1 },
    ],
  },
  {
    id: "haus",
    name: "Haus & Möbel",
    emoji: "🏠",
    from: "#56ccf2",
    to: "#2f80ed",
    words: [
      { de: "das Haus", en: "house", es: "la casa", emoji: "🏠", lvl: 1 },
      { de: "die Wohnung", en: "flat", es: "el piso", emoji: "🏢", lvl: 2 },
      { de: "das Zimmer", en: "room", es: "la habitación", emoji: "🚪", lvl: 1 },
      { de: "die Küche", en: "kitchen", es: "la cocina", emoji: "🍳", lvl: 1 },
      { de: "das Badezimmer", en: "bathroom", es: "el baño", emoji: "🛁", lvl: 1 },
      { de: "das Schlafzimmer", en: "bedroom", es: "el dormitorio", emoji: "🛏️", lvl: 1 },
      { de: "das Wohnzimmer", en: "living room", es: "el salón", emoji: "🛋️", lvl: 1 },
      { de: "der Garten", en: "garden", es: "el jardín", emoji: "🌷", lvl: 1 },
      { de: "die Tür", en: "door", es: "la puerta", emoji: "🚪", lvl: 1 },
      { de: "das Fenster", en: "window", es: "la ventana", emoji: "🪟", lvl: 1 },
      { de: "die Wand", en: "wall", es: "la pared", emoji: "🧱", lvl: 2 },
      { de: "der Boden", en: "floor", es: "el suelo", emoji: "🟫", lvl: 2 },
      { de: "das Dach", en: "roof", es: "el tejado", emoji: "🏚️", lvl: 2 },
      { de: "die Treppe", en: "stairs", es: "la escalera", emoji: "🪜", lvl: 2 },
      { de: "der Schlüssel", en: "key", es: "la llave", emoji: "🔑", lvl: 1 },
      { de: "das Bett", en: "bed", es: "la cama", emoji: "🛏️", lvl: 1 },
      { de: "der Schrank", en: "wardrobe", es: "el armario", emoji: "🗄️", lvl: 2 },
      { de: "das Sofa", en: "sofa", es: "el sofá", emoji: "🛋️", lvl: 1 },
      { de: "der Sessel", en: "armchair", es: "el sillón", emoji: "💺", lvl: 2 },
      { de: "die Lampe", en: "lamp", es: "la lámpara", emoji: "💡", lvl: 1 },
      { de: "der Spiegel", en: "mirror", es: "el espejo", emoji: "🪞", lvl: 2 },
      { de: "das Bild", en: "picture", es: "el cuadro", emoji: "🖼️", lvl: 1 },
      { de: "der Teppich", en: "carpet", es: "la alfombra", emoji: "🧶", lvl: 2 },
      { de: "der Vorhang", en: "curtain", es: "la cortina", emoji: "🎭", lvl: 3 },
      { de: "der Kühlschrank", en: "fridge", es: "la nevera", emoji: "🧊", lvl: 2 },
      { de: "der Backofen", en: "oven", es: "el horno", emoji: "♨️", lvl: 2 },
      { de: "die Mikrowelle", en: "microwave", es: "el microondas", emoji: "⏲️", lvl: 3 },
      { de: "die Waschmaschine", en: "washing machine", es: "la lavadora", emoji: "🌀", lvl: 2 },
      { de: "der Fernseher", en: "television", es: "la televisión", emoji: "📺", lvl: 1 },
      { de: "das Telefon", en: "telephone", es: "el teléfono", emoji: "📞", lvl: 1 },
      { de: "die Dusche", en: "shower", es: "la ducha", emoji: "🚿", lvl: 1 },
      { de: "die Badewanne", en: "bathtub", es: "la bañera", emoji: "🛁", lvl: 2 },
      { de: "die Toilette", en: "toilet", es: "el váter", emoji: "🚽", lvl: 1 },
      { de: "das Waschbecken", en: "sink", es: "el lavabo", emoji: "🚰", lvl: 3 },
      { de: "die Seife", en: "soap", es: "el jabón", emoji: "🧼", lvl: 2 },
      { de: "das Handtuch", en: "towel", es: "la toalla", emoji: "🧖", lvl: 2 },
      { de: "die Zahnbürste", en: "toothbrush", es: "el cepillo de dientes", emoji: "🪥", lvl: 1 },
      { de: "der Müll", en: "rubbish", es: "la basura", emoji: "🗑️", lvl: 2 },
      { de: "die Kerze", en: "candle", es: "la vela", emoji: "🕯️", lvl: 2 },
      { de: "der Briefkasten", en: "letter box", es: "el buzón", emoji: "📮", lvl: 3 },
    ],
  },
  {
    id: "spielzeug",
    name: "Spielzeug & Freizeit",
    emoji: "🧸",
    from: "#ff5f6d",
    to: "#ffc371",
    words: [
      { de: "das Spielzeug", en: "toy", es: "el juguete", emoji: "🧸", lvl: 1 },
      { de: "der Ball", en: "ball", es: "la pelota", emoji: "🏐", lvl: 1 },
      { de: "die Puppe", en: "doll", es: "la muñeca", emoji: "🎎", lvl: 1 },
      { de: "der Teddybär", en: "teddy bear", es: "el osito de peluche", emoji: "🧸", lvl: 1 },
      { de: "der Drachen", en: "kite", es: "la cometa", emoji: "🪁", lvl: 2 },
      { de: "der Luftballon", en: "balloon", es: "el globo", emoji: "🎈", lvl: 1 },
      { de: "das Puzzle", en: "puzzle", es: "el rompecabezas", emoji: "🧩", lvl: 2 },
      { de: "das Spiel", en: "game", es: "el juego", emoji: "🎲", lvl: 1 },
      { de: "das Videospiel", en: "video game", es: "el videojuego", emoji: "🎮", lvl: 2 },
      { de: "die Spielkarte", en: "playing card", es: "la carta", emoji: "🃏", lvl: 2 },
      { de: "die Bausteine", en: "building blocks", es: "los bloques", emoji: "🧱", lvl: 2 },
      { de: "die Eisenbahn", en: "toy train", es: "el tren de juguete", emoji: "🚂", lvl: 2 },
      { de: "die Rutsche", en: "slide", es: "el tobogán", emoji: "🛝", lvl: 1 },
      { de: "die Schaukel", en: "swing", es: "el columpio", emoji: "🤸", lvl: 1 },
      { de: "das Jojo", en: "yo-yo", es: "el yoyó", emoji: "🪀", lvl: 3 },
      { de: "der Kreisel", en: "spinning top", es: "la peonza", emoji: "🌀", lvl: 3 },
      { de: "die Murmel", en: "marble", es: "la canica", emoji: "🔮", lvl: 3 },
      { de: "das Kuscheltier", en: "cuddly toy", es: "el peluche", emoji: "🐻", lvl: 1 },
      { de: "das Märchen", en: "fairy tale", es: "el cuento", emoji: "🏰", lvl: 2 },
      { de: "der Zauberer", en: "wizard", es: "el mago", emoji: "🧙", lvl: 2 },
      { de: "die Fee", en: "fairy", es: "el hada", emoji: "🧚", lvl: 2 },
      { de: "der Pirat", en: "pirate", es: "el pirata", emoji: "🏴‍☠️", lvl: 2 },
      { de: "der Ritter", en: "knight", es: "el caballero", emoji: "⚔️", lvl: 2 },
      { de: "die Prinzessin", en: "princess", es: "la princesa", emoji: "👸", lvl: 1 },
      { de: "der König", en: "king", es: "el rey", emoji: "🤴", lvl: 1 },
      { de: "die Königin", en: "queen", es: "la reina", emoji: "👑", lvl: 1 },
      { de: "das Geschenk", en: "present", es: "el regalo", emoji: "🎁", lvl: 1 },
      { de: "die Party", en: "party", es: "la fiesta", emoji: "🥳", lvl: 1 },
      { de: "der Zirkus", en: "circus", es: "el circo", emoji: "🎪", lvl: 2 },
      { de: "der Clown", en: "clown", es: "el payaso", emoji: "🤡", lvl: 1 },
      { de: "das Kino", en: "cinema", es: "el cine", emoji: "🎬", lvl: 1 },
      { de: "tanzen", en: "to dance", es: "bailar", emoji: "💃", lvl: 1 },
      { de: "singen", en: "to sing", es: "cantar", emoji: "🎤", lvl: 1 },
      { de: "lachen", en: "to laugh", es: "reír", emoji: "😂", lvl: 1 },
      { de: "der Spielplatz", en: "playground", es: "el parque infantil", emoji: "🛝", lvl: 1 },
      { de: "der Witz", en: "joke", es: "el chiste", emoji: "🤣", lvl: 3 },
      { de: "der Roboter", en: "robot", es: "el robot", emoji: "🤖", lvl: 1 },
    ],
  },
  {
    id: "gefuehle",
    name: "Gefühle",
    emoji: "😀",
    from: "#fbc2eb",
    to: "#a6c1ee",
    words: [
      { de: "glücklich", en: "happy", es: "feliz", emoji: "😀", lvl: 1 },
      { de: "traurig", en: "sad", es: "triste", emoji: "😢", lvl: 1 },
      { de: "wütend", en: "angry", es: "enfadado", emoji: "😠", lvl: 1 },
      { de: "müde", en: "tired", es: "cansado", emoji: "😴", lvl: 1 },
      { de: "die Angst", en: "fear", es: "el miedo", emoji: "😨", lvl: 1 },
      { de: "mutig", en: "brave", es: "valiente", emoji: "🦁", lvl: 2 },
      { de: "überrascht", en: "surprised", es: "sorprendido", emoji: "😲", lvl: 2 },
      { de: "verliebt", en: "in love", es: "enamorado", emoji: "😍", lvl: 2 },
      { de: "stolz", en: "proud", es: "orgulloso", emoji: "😌", lvl: 3 },
      { de: "schüchtern", en: "shy", es: "tímido", emoji: "🫣", lvl: 3 },
      { de: "nervös", en: "nervous", es: "nervioso", emoji: "😬", lvl: 3 },
      { de: "gelangweilt", en: "bored", es: "aburrido", emoji: "🥱", lvl: 2 },
      { de: "aufgeregt", en: "excited", es: "emocionado", emoji: "🤩", lvl: 2 },
      { de: "krank", en: "sick", es: "enfermo", emoji: "🤒", lvl: 1 },
      { de: "gesund", en: "healthy", es: "sano", emoji: "💚", lvl: 2 },
      { de: "hungrig", en: "hungry", es: "hambriento", emoji: "😋", lvl: 1 },
      { de: "durstig", en: "thirsty", es: "sediento", emoji: "🥤", lvl: 2 },
      { de: "lustig", en: "funny", es: "divertido", emoji: "😆", lvl: 1 },
      { de: "nett", en: "nice", es: "simpático", emoji: "🥰", lvl: 1 },
      { de: "die Freude", en: "joy", es: "la alegría", emoji: "😄", lvl: 2 },
      { de: "die Liebe", en: "love", es: "el amor", emoji: "❤️", lvl: 1 },
      { de: "das Lächeln", en: "smile", es: "la sonrisa", emoji: "😊", lvl: 2 },
      { de: "weinen", en: "to cry", es: "llorar", emoji: "😭", lvl: 1 },
      { de: "die Träne", en: "tear", es: "la lágrima", emoji: "💧", lvl: 3 },
      { de: "der Traum", en: "dream", es: "el sueño", emoji: "💭", lvl: 2 },
      { de: "ruhig", en: "calm", es: "tranquilo", emoji: "🧘", lvl: 2 },
      { de: "laut", en: "loud", es: "ruidoso", emoji: "📢", lvl: 2 },
      { de: "leise", en: "quiet", es: "silencioso", emoji: "🤫", lvl: 2 },
      { de: "allein", en: "alone", es: "solo", emoji: "🙍", lvl: 2 },
      { de: "zusammen", en: "together", es: "juntos", emoji: "🫂", lvl: 2 },
      { de: "der Kuss", en: "kiss", es: "el beso", emoji: "😘", lvl: 2 },
      { de: "die Umarmung", en: "hug", es: "el abrazo", emoji: "🤗", lvl: 2 },
    ],
  },
  {
    id: "stadt",
    name: "Stadt & Orte",
    emoji: "🏙️",
    from: "#00c6ff",
    to: "#0072ff",
    words: [
      { de: "die Stadt", en: "city", es: "la ciudad", emoji: "🏙️", lvl: 1 },
      { de: "das Dorf", en: "village", es: "el pueblo", emoji: "🏘️", lvl: 2 },
      { de: "der Markt", en: "market", es: "el mercado", emoji: "🧺", lvl: 2 },
      { de: "der Supermarkt", en: "supermarket", es: "el supermercado", emoji: "🛒", lvl: 1 },
      { de: "das Geschäft", en: "shop", es: "la tienda", emoji: "🏪", lvl: 1 },
      { de: "die Bäckerei", en: "bakery", es: "la panadería", emoji: "🥐", lvl: 2 },
      { de: "die Apotheke", en: "pharmacy", es: "la farmacia", emoji: "💊", lvl: 2 },
      { de: "das Krankenhaus", en: "hospital", es: "el hospital", emoji: "🏥", lvl: 1 },
      { de: "die Polizei", en: "police", es: "la policía", emoji: "👮", lvl: 1 },
      { de: "die Feuerwehr", en: "fire brigade", es: "los bomberos", emoji: "🚒", lvl: 1 },
      { de: "die Post", en: "post office", es: "la oficina de correos", emoji: "📬", lvl: 2 },
      { de: "die Bank", en: "bank", es: "el banco", emoji: "🏦", lvl: 2 },
      { de: "das Rathaus", en: "town hall", es: "el ayuntamiento", emoji: "🏢", lvl: 3 },
      { de: "die Kirche", en: "church", es: "la iglesia", emoji: "⛪", lvl: 2 },
      { de: "das Schloss", en: "castle", es: "el castillo", emoji: "🏰", lvl: 1 },
      { de: "der Turm", en: "tower", es: "la torre", emoji: "🗼", lvl: 2 },
      { de: "das Museum", en: "museum", es: "el museo", emoji: "🏛️", lvl: 2 },
      { de: "die Bibliothek", en: "library", es: "la biblioteca", emoji: "📚", lvl: 2 },
      { de: "das Restaurant", en: "restaurant", es: "el restaurante", emoji: "🍽️", lvl: 1 },
      { de: "das Café", en: "café", es: "la cafetería", emoji: "☕", lvl: 1 },
      { de: "der Park", en: "park", es: "el parque", emoji: "🌳", lvl: 1 },
      { de: "der Zoo", en: "zoo", es: "el zoo", emoji: "🦁", lvl: 1 },
      { de: "das Schwimmbad", en: "swimming pool", es: "la piscina", emoji: "🏊", lvl: 1 },
      { de: "das Stadion", en: "stadium", es: "el estadio", emoji: "🏟️", lvl: 2 },
      { de: "der Platz", en: "square", es: "la plaza", emoji: "📍", lvl: 2 },
      { de: "der Brunnen", en: "fountain", es: "la fuente", emoji: "⛲", lvl: 2 },
      { de: "der Weg", en: "path", es: "el camino", emoji: "🛤️", lvl: 2 },
      { de: "der Zaun", en: "fence", es: "la valla", emoji: "🚧", lvl: 3 },
      { de: "die Mauer", en: "wall", es: "el muro", emoji: "🧱", lvl: 3 },
      { de: "die Fabrik", en: "factory", es: "la fábrica", emoji: "🏭", lvl: 3 },
      { de: "der Bauernhof", en: "farm", es: "la granja", emoji: "🌾", lvl: 1 },
      { de: "die Adresse", en: "address", es: "la dirección", emoji: "✉️", lvl: 3 },
      { de: "der Eingang", en: "entrance", es: "la entrada", emoji: "🚪", lvl: 2 },
      { de: "der Ausgang", en: "exit", es: "la salida", emoji: "🏃‍♂️", lvl: 2 },
    ],
  },
  {
    id: "sport",
    name: "Sport & Hobbys",
    emoji: "⚽",
    from: "#11998e",
    to: "#38ef7d",
    words: [
      { de: "der Sport", en: "sport", es: "el deporte", emoji: "🏅", lvl: 1 },
      { de: "der Fußball", en: "football", es: "el fútbol", emoji: "⚽", lvl: 1 },
      { de: "der Basketball", en: "basketball", es: "el baloncesto", emoji: "🏀", lvl: 1 },
      { de: "das Tennis", en: "tennis", es: "el tenis", emoji: "🎾", lvl: 1 },
      { de: "das Schwimmen", en: "swimming", es: "la natación", emoji: "🏊", lvl: 1 },
      { de: "das Rennen", en: "race", es: "la carrera", emoji: "🏃", lvl: 2 },
      { de: "das Radfahren", en: "cycling", es: "el ciclismo", emoji: "🚴", lvl: 2 },
      { de: "das Skifahren", en: "skiing", es: "el esquí", emoji: "⛷️", lvl: 2 },
      { de: "das Schlittschuhlaufen", en: "ice skating", es: "el patinaje", emoji: "⛸️", lvl: 3 },
      { de: "das Reiten", en: "horse riding", es: "la equitación", emoji: "🏇", lvl: 2 },
      { de: "das Klettern", en: "climbing", es: "la escalada", emoji: "🧗", lvl: 2 },
      { de: "das Turnen", en: "gymnastics", es: "la gimnasia", emoji: "🤸", lvl: 2 },
      { de: "der Volleyball", en: "volleyball", es: "el voleibol", emoji: "🏐", lvl: 2 },
      { de: "das Tischtennis", en: "table tennis", es: "el ping-pong", emoji: "🏓", lvl: 2 },
      { de: "das Golf", en: "golf", es: "el golf", emoji: "⛳", lvl: 3 },
      { de: "das Boxen", en: "boxing", es: "el boxeo", emoji: "🥊", lvl: 3 },
      { de: "das Angeln", en: "fishing", es: "la pesca", emoji: "🎣", lvl: 2 },
      { de: "das Segeln", en: "sailing", es: "la vela", emoji: "⛵", lvl: 3 },
      { de: "das Tor", en: "goal", es: "el gol", emoji: "🥅", lvl: 1 },
      { de: "der Sieg", en: "victory", es: "la victoria", emoji: "🏆", lvl: 2 },
      { de: "gewinnen", en: "to win", es: "ganar", emoji: "🥇", lvl: 1 },
      { de: "verlieren", en: "to lose", es: "perder", emoji: "😞", lvl: 2 },
      { de: "die Mannschaft", en: "team", es: "el equipo", emoji: "👥", lvl: 2 },
      { de: "der Spieler", en: "player", es: "el jugador", emoji: "🎽", lvl: 2 },
      { de: "der Schiedsrichter", en: "referee", es: "el árbitro", emoji: "🟨", lvl: 3 },
      { de: "die Medaille", en: "medal", es: "la medalla", emoji: "🥇", lvl: 2 },
      { de: "der Pokal", en: "trophy", es: "el trofeo", emoji: "🏆", lvl: 1 },
      { de: "das Hobby", en: "hobby", es: "la afición", emoji: "🎨", lvl: 2 },
      { de: "das Foto", en: "photo", es: "la foto", emoji: "📷", lvl: 1 },
      { de: "die Kamera", en: "camera", es: "la cámara", emoji: "🎥", lvl: 2 },
      { de: "die Gitarre", en: "guitar", es: "la guitarra", emoji: "🎸", lvl: 1 },
      { de: "das Klavier", en: "piano", es: "el piano", emoji: "🎹", lvl: 1 },
      { de: "die Trommel", en: "drum", es: "el tambor", emoji: "🥁", lvl: 2 },
      { de: "die Flöte", en: "flute", es: "la flauta", emoji: "🎶", lvl: 3 },
      { de: "werfen", en: "to throw", es: "lanzar", emoji: "🤾", lvl: 2 },
      { de: "fangen", en: "to catch", es: "atrapar", emoji: "🙌", lvl: 2 },
    ],
  },
  {
    id: "berufe",
    name: "Berufe & Arbeit",
    emoji: "👩‍🚒",
    from: "#654ea3",
    to: "#eaafc8",
    words: [
      { de: "der Beruf", en: "job", es: "la profesión", emoji: "💼", lvl: 2 },
      { de: "der Pilot", en: "pilot", es: "el piloto", emoji: "👨‍✈️", lvl: 1 },
      { de: "der Kapitän", en: "captain", es: "el capitán", emoji: "⚓", lvl: 3 },
      { de: "der Astronaut", en: "astronaut", es: "el astronauta", emoji: "🧑‍🚀", lvl: 1 },
      { de: "der Zahnarzt", en: "dentist", es: "el dentista", emoji: "🦷", lvl: 2 },
      { de: "die Krankenschwester", en: "nurse", es: "la enfermera", emoji: "💉", lvl: 2 },
      { de: "der Tierarzt", en: "vet", es: "el veterinario", emoji: "🐾", lvl: 2 },
      { de: "der Bäcker", en: "baker", es: "el panadero", emoji: "🥖", lvl: 1 },
      { de: "der Metzger", en: "butcher", es: "el carnicero", emoji: "🔪", lvl: 3 },
      { de: "der Friseur", en: "hairdresser", es: "el peluquero", emoji: "💇", lvl: 2 },
      { de: "der Verkäufer", en: "shop assistant", es: "el vendedor", emoji: "🛍️", lvl: 2 },
      { de: "der Kellner", en: "waiter", es: "el camarero", emoji: "🧾", lvl: 2 },
      { de: "der Gärtner", en: "gardener", es: "el jardinero", emoji: "🌻", lvl: 2 },
      { de: "der Maler", en: "painter", es: "el pintor", emoji: "🖌️", lvl: 2 },
      { de: "der Musiker", en: "musician", es: "el músico", emoji: "🎻", lvl: 2 },
      { de: "der Sänger", en: "singer", es: "el cantante", emoji: "🎤", lvl: 1 },
      { de: "der Schauspieler", en: "actor", es: "el actor", emoji: "🎭", lvl: 2 },
      { de: "der Tänzer", en: "dancer", es: "el bailarín", emoji: "🕺", lvl: 2 },
      { de: "der Fußballspieler", en: "footballer", es: "el futbolista", emoji: "⚽", lvl: 1 },
      { de: "der Anwalt", en: "lawyer", es: "el abogado", emoji: "⚖️", lvl: 3 },
      { de: "der Richter", en: "judge", es: "el juez", emoji: "🧑‍⚖️", lvl: 3 },
      { de: "der Ingenieur", en: "engineer", es: "el ingeniero", emoji: "⚙️", lvl: 3 },
      { de: "der Wissenschaftler", en: "scientist", es: "el científico", emoji: "🧑‍🔬", lvl: 2 },
      { de: "der Erfinder", en: "inventor", es: "el inventor", emoji: "💡", lvl: 3 },
      { de: "der Briefträger", en: "postman", es: "el cartero", emoji: "📯", lvl: 2 },
      { de: "der Fahrer", en: "driver", es: "el conductor", emoji: "🚗", lvl: 2 },
      { de: "der Soldat", en: "soldier", es: "el soldado", emoji: "🪖", lvl: 3 },
      { de: "der Journalist", en: "journalist", es: "el periodista", emoji: "📰", lvl: 3 },
      { de: "der Fotograf", en: "photographer", es: "el fotógrafo", emoji: "📸", lvl: 2 },
      { de: "der Programmierer", en: "programmer", es: "el programador", emoji: "👨‍💻", lvl: 2 },
      { de: "der Chef", en: "boss", es: "el jefe", emoji: "🧑‍💼", lvl: 2 },
      { de: "das Büro", en: "office", es: "la oficina", emoji: "🏢", lvl: 2 },
      { de: "das Geld", en: "money", es: "el dinero", emoji: "💰", lvl: 1 },
      { de: "arbeiten", en: "to work", es: "trabajar", emoji: "🔨", lvl: 1 },
    ],
  },
  {
    id: "zeit",
    name: "Zeit & Kalender",
    emoji: "🕐",
    from: "#ff512f",
    to: "#dd2476",
    words: [
      { de: "der Tag", en: "day", es: "el día", emoji: "📅", lvl: 1 },
      { de: "die Woche", en: "week", es: "la semana", emoji: "🗓️", lvl: 1 },
      { de: "der Monat", en: "month", es: "el mes", emoji: "📆", lvl: 1 },
      { de: "das Jahr", en: "year", es: "el año", emoji: "🎆", lvl: 1 },
      { de: "die Stunde", en: "hour", es: "la hora", emoji: "⏰", lvl: 1 },
      { de: "die Minute", en: "minute", es: "el minuto", emoji: "⏱️", lvl: 2 },
      { de: "die Sekunde", en: "second", es: "el segundo", emoji: "⏲️", lvl: 2 },
      { de: "heute", en: "today", es: "hoy", emoji: "📌", lvl: 1 },
      { de: "morgen", en: "tomorrow", es: "mañana", emoji: "🌅", lvl: 1 },
      { de: "gestern", en: "yesterday", es: "ayer", emoji: "⬅️", lvl: 1 },
      { de: "jetzt", en: "now", es: "ahora", emoji: "▶️", lvl: 2 },
      { de: "früh", en: "early", es: "temprano", emoji: "🐓", lvl: 2 },
      { de: "spät", en: "late", es: "tarde", emoji: "🌙", lvl: 2 },
      { de: "der Morgen", en: "morning", es: "la mañana", emoji: "🌄", lvl: 1 },
      { de: "der Mittag", en: "noon", es: "el mediodía", emoji: "🕛", lvl: 2 },
      { de: "der Abend", en: "evening", es: "la tarde", emoji: "🌆", lvl: 1 },
      { de: "die Nacht", en: "night", es: "la noche", emoji: "🌃", lvl: 1 },
      { de: "Montag", en: "Monday", es: "el lunes", emoji: "1️⃣", lvl: 1 },
      { de: "Dienstag", en: "Tuesday", es: "el martes", emoji: "2️⃣", lvl: 1 },
      { de: "Mittwoch", en: "Wednesday", es: "el miércoles", emoji: "3️⃣", lvl: 1 },
      { de: "Donnerstag", en: "Thursday", es: "el jueves", emoji: "4️⃣", lvl: 1 },
      { de: "Freitag", en: "Friday", es: "el viernes", emoji: "5️⃣", lvl: 1 },
      { de: "Samstag", en: "Saturday", es: "el sábado", emoji: "6️⃣", lvl: 1 },
      { de: "Sonntag", en: "Sunday", es: "el domingo", emoji: "7️⃣", lvl: 1 },
      { de: "Januar", en: "January", es: "enero", emoji: "❄️", lvl: 2 },
      { de: "Februar", en: "February", es: "febrero", emoji: "🎭", lvl: 2 },
      { de: "März", en: "March", es: "marzo", emoji: "🌱", lvl: 2 },
      { de: "April", en: "April", es: "abril", emoji: "🌦️", lvl: 2 },
      { de: "Mai", en: "May", es: "mayo", emoji: "🌸", lvl: 2 },
      { de: "Juni", en: "June", es: "junio", emoji: "☀️", lvl: 2 },
      { de: "Juli", en: "July", es: "julio", emoji: "🏖️", lvl: 2 },
      { de: "August", en: "August", es: "agosto", emoji: "🍦", lvl: 2 },
      { de: "September", en: "September", es: "septiembre", emoji: "🍁", lvl: 2 },
      { de: "Oktober", en: "October", es: "octubre", emoji: "🎃", lvl: 2 },
      { de: "November", en: "November", es: "noviembre", emoji: "🌫️", lvl: 2 },
      { de: "Dezember", en: "December", es: "diciembre", emoji: "🎄", lvl: 2 },
      { de: "der Kalender", en: "calendar", es: "el calendario", emoji: "🗓️", lvl: 2 },
    ],
  },
  {
    id: "reisen",
    name: "Urlaub & Reisen",
    emoji: "✈️",
    from: "#f857a6",
    to: "#ff5858",
    words: [
      { de: "die Reise", en: "trip", es: "el viaje", emoji: "🌏", lvl: 1 },
      { de: "der Koffer", en: "suitcase", es: "la maleta", emoji: "🧳", lvl: 1 },
      { de: "der Pass", en: "passport", es: "el pasaporte", emoji: "🛂", lvl: 2 },
      { de: "die Landkarte", en: "map", es: "el mapa", emoji: "🗺️", lvl: 2 },
      { de: "der Kompass", en: "compass", es: "la brújula", emoji: "🧭", lvl: 3 },
      { de: "das Hotel", en: "hotel", es: "el hotel", emoji: "🏨", lvl: 1 },
      { de: "das Zelt", en: "tent", es: "la tienda de campaña", emoji: "⛺", lvl: 2 },
      { de: "der Campingplatz", en: "campsite", es: "el camping", emoji: "🏕️", lvl: 2 },
      { de: "das Souvenir", en: "souvenir", es: "el recuerdo", emoji: "🎁", lvl: 3 },
      { de: "die Sonnencreme", en: "sun cream", es: "la crema solar", emoji: "🧴", lvl: 2 },
      { de: "die Grenze", en: "border", es: "la frontera", emoji: "🚧", lvl: 3 },
      { de: "das Land", en: "country", es: "el país", emoji: "🌎", lvl: 1 },
      { de: "die Hauptstadt", en: "capital", es: "la capital", emoji: "🏛️", lvl: 2 },
      { de: "Spanien", en: "Spain", es: "España", emoji: "🇪🇸", lvl: 1 },
      { de: "England", en: "England", es: "Inglaterra", emoji: "🇬🇧", lvl: 1 },
      { de: "Deutschland", en: "Germany", es: "Alemania", emoji: "🇩🇪", lvl: 1 },
      { de: "Frankreich", en: "France", es: "Francia", emoji: "🇫🇷", lvl: 2 },
      { de: "Italien", en: "Italy", es: "Italia", emoji: "🇮🇹", lvl: 2 },
      { de: "Amerika", en: "America", es: "América", emoji: "🇺🇸", lvl: 2 },
      { de: "das Abenteuer", en: "adventure", es: "la aventura", emoji: "🌋", lvl: 2 },
      { de: "der Ausflug", en: "excursion", es: "la excursión", emoji: "🚌", lvl: 2 },
      { de: "das Picknick", en: "picnic", es: "el pícnic", emoji: "🧺", lvl: 2 },
      { de: "wandern", en: "to hike", es: "hacer senderismo", emoji: "🥾", lvl: 2 },
      { de: "schwimmen", en: "to swim", es: "nadar", emoji: "🏊", lvl: 1 },
      { de: "tauchen", en: "to dive", es: "bucear", emoji: "🤿", lvl: 2 },
      { de: "die Welle", en: "wave", es: "la ola", emoji: "🌊", lvl: 2 },
      { de: "die Muschel", en: "shell", es: "la concha", emoji: "🐚", lvl: 2 },
      { de: "die Sandburg", en: "sandcastle", es: "el castillo de arena", emoji: "🏰", lvl: 1 },
      { de: "der Liegestuhl", en: "deck chair", es: "la tumbona", emoji: "🪑", lvl: 3 },
      { de: "der Sonnenschirm", en: "parasol", es: "la sombrilla", emoji: "⛱️", lvl: 2 },
      { de: "die Ankunft", en: "arrival", es: "la llegada", emoji: "🛬", lvl: 3 },
      { de: "die Abfahrt", en: "departure", es: "la salida", emoji: "🛫", lvl: 3 },
    ],
  },
  {
    id: "verben",
    name: "Alltagsverben",
    emoji: "🏃",
    from: "#7f00ff",
    to: "#e100ff",
    words: [
      { de: "gehen", en: "to go", es: "ir", emoji: "🚶", lvl: 1 },
      { de: "laufen", en: "to run", es: "correr", emoji: "🏃", lvl: 1 },
      { de: "springen", en: "to jump", es: "saltar", emoji: "🦘", lvl: 1 },
      { de: "essen", en: "to eat", es: "comer", emoji: "🍽️", lvl: 1 },
      { de: "trinken", en: "to drink", es: "beber", emoji: "🥤", lvl: 1 },
      { de: "schlafen", en: "to sleep", es: "dormir", emoji: "😴", lvl: 1 },
      { de: "spielen", en: "to play", es: "jugar", emoji: "🎮", lvl: 1 },
      { de: "sehen", en: "to see", es: "ver", emoji: "👀", lvl: 1 },
      { de: "kommen", en: "to come", es: "venir", emoji: "🚶‍♂️", lvl: 1 },
      { de: "geben", en: "to give", es: "dar", emoji: "🎁", lvl: 2 },
      { de: "nehmen", en: "to take", es: "tomar", emoji: "✊", lvl: 2 },
      { de: "machen", en: "to make", es: "hacer", emoji: "🛠️", lvl: 1 },
      { de: "sagen", en: "to say", es: "decir", emoji: "💬", lvl: 1 },
      { de: "fragen", en: "to ask", es: "preguntar", emoji: "❓", lvl: 1 },
      { de: "antworten", en: "to answer", es: "responder", emoji: "✅", lvl: 2 },
      { de: "helfen", en: "to help", es: "ayudar", emoji: "🤝", lvl: 1 },
      { de: "kaufen", en: "to buy", es: "comprar", emoji: "🛒", lvl: 1 },
      { de: "bezahlen", en: "to pay", es: "pagar", emoji: "💳", lvl: 2 },
      { de: "suchen", en: "to look for", es: "buscar", emoji: "🔍", lvl: 2 },
      { de: "finden", en: "to find", es: "encontrar", emoji: "🔎", lvl: 2 },
      { de: "öffnen", en: "to open", es: "abrir", emoji: "🔓", lvl: 2 },
      { de: "schließen", en: "to close", es: "cerrar", emoji: "🔒", lvl: 2 },
      { de: "beginnen", en: "to begin", es: "empezar", emoji: "▶️", lvl: 2 },
      { de: "aufhören", en: "to stop", es: "parar", emoji: "🛑", lvl: 2 },
      { de: "warten", en: "to wait", es: "esperar", emoji: "⏳", lvl: 2 },
      { de: "denken", en: "to think", es: "pensar", emoji: "🤔", lvl: 2 },
      { de: "wissen", en: "to know", es: "saber", emoji: "🧠", lvl: 2 },
      { de: "vergessen", en: "to forget", es: "olvidar", emoji: "🙈", lvl: 3 },
      { de: "lieben", en: "to love", es: "amar", emoji: "❤️", lvl: 1 },
      { de: "mögen", en: "to like", es: "gustar", emoji: "👍", lvl: 1 },
      { de: "brauchen", en: "to need", es: "necesitar", emoji: "❗", lvl: 2 },
      { de: "wohnen", en: "to live", es: "vivir", emoji: "🏠", lvl: 1 },
      { de: "kochen", en: "to cook", es: "cocinar", emoji: "🍳", lvl: 1 },
      { de: "waschen", en: "to wash", es: "lavar", emoji: "🧼", lvl: 2 },
      { de: "putzen", en: "to clean", es: "limpiar", emoji: "🧹", lvl: 2 },
      { de: "tragen", en: "to carry", es: "llevar", emoji: "💪", lvl: 2 },
      { de: "ziehen", en: "to pull", es: "tirar", emoji: "🧲", lvl: 3 },
      { de: "drücken", en: "to push", es: "empujar", emoji: "👊", lvl: 3 },
      { de: "fallen", en: "to fall", es: "caer", emoji: "⬇️", lvl: 2 },
      { de: "sitzen", en: "to sit", es: "sentarse", emoji: "🪑", lvl: 1 },
    ],
  },
  {
    id: "adjektive",
    name: "Wichtige Adjektive",
    emoji: "✨",
    from: "#fc466b",
    to: "#3f5efb",
    words: [
      { de: "groß", en: "big", es: "grande", emoji: "🐘", lvl: 1 },
      { de: "klein", en: "small", es: "pequeño", emoji: "🐭", lvl: 1 },
      { de: "lang", en: "long", es: "largo", emoji: "📏", lvl: 1 },
      { de: "kurz", en: "short", es: "corto", emoji: "✂️", lvl: 1 },
      { de: "neu", en: "new", es: "nuevo", emoji: "✨", lvl: 1 },
      { de: "alt", en: "old", es: "viejo", emoji: "🏚️", lvl: 1 },
      { de: "jung", en: "young", es: "joven", emoji: "🧒", lvl: 1 },
      { de: "gut", en: "good", es: "bueno", emoji: "👍", lvl: 1 },
      { de: "schlecht", en: "bad", es: "malo", emoji: "👎", lvl: 1 },
      { de: "schön", en: "beautiful", es: "bonito", emoji: "🌹", lvl: 1 },
      { de: "hässlich", en: "ugly", es: "feo", emoji: "👹", lvl: 2 },
      { de: "stark", en: "strong", es: "fuerte", emoji: "💪", lvl: 1 },
      { de: "schwach", en: "weak", es: "débil", emoji: "🍃", lvl: 2 },
      { de: "schwer", en: "heavy", es: "pesado", emoji: "🏋️", lvl: 2 },
      { de: "leicht", en: "light", es: "ligero", emoji: "🪶", lvl: 2 },
      { de: "voll", en: "full", es: "lleno", emoji: "🌕", lvl: 2 },
      { de: "leer", en: "empty", es: "vacío", emoji: "📭", lvl: 2 },
      { de: "sauber", en: "clean", es: "limpio", emoji: "🧽", lvl: 2 },
      { de: "schmutzig", en: "dirty", es: "sucio", emoji: "💩", lvl: 2 },
      { de: "nass", en: "wet", es: "mojado", emoji: "💦", lvl: 2 },
      { de: "trocken", en: "dry", es: "seco", emoji: "🌵", lvl: 2 },
      { de: "süß", en: "sweet", es: "dulce", emoji: "🍭", lvl: 1 },
      { de: "sauer", en: "sour", es: "ácido", emoji: "🍋", lvl: 2 },
      { de: "reich", en: "rich", es: "rico", emoji: "💰", lvl: 3 },
      { de: "arm", en: "poor", es: "pobre", emoji: "🪙", lvl: 3 },
      { de: "teuer", en: "expensive", es: "caro", emoji: "💎", lvl: 2 },
      { de: "billig", en: "cheap", es: "barato", emoji: "🏷️", lvl: 2 },
      { de: "richtig", en: "right", es: "correcto", emoji: "✅", lvl: 1 },
      { de: "falsch", en: "wrong", es: "falso", emoji: "❌", lvl: 1 },
      { de: "einfach", en: "easy", es: "fácil", emoji: "👌", lvl: 2 },
      { de: "schwierig", en: "difficult", es: "difícil", emoji: "🤯", lvl: 2 },
      { de: "wichtig", en: "important", es: "importante", emoji: "‼️", lvl: 2 },
      { de: "lecker", en: "tasty", es: "delicioso", emoji: "😋", lvl: 1 },
      { de: "kaputt", en: "broken", es: "roto", emoji: "💔", lvl: 2 },
      { de: "fertig", en: "finished", es: "terminado", emoji: "🏁", lvl: 2 },
      { de: "offen", en: "open", es: "abierto", emoji: "🔓", lvl: 2 },
      { de: "geschlossen", en: "closed", es: "cerrado", emoji: "🔒", lvl: 2 },
      { de: "frei", en: "free", es: "libre", emoji: "🕊️", lvl: 2 },
      { de: "gleich", en: "same", es: "igual", emoji: "🪞", lvl: 3 },
      { de: "anders", en: "different", es: "diferente", emoji: "🎭", lvl: 3 },
    ],
  },
  {
    id: "floskeln",
    name: "Erste Sätze",
    emoji: "🗣️",
    from: "#642b73",
    to: "#c6426e",
    words: [
      { de: "Hallo", en: "Hello", es: "Hola", emoji: "👋", lvl: 1 },
      { de: "Tschüss", en: "Bye", es: "Adiós", emoji: "🙋", lvl: 1 },
      { de: "Guten Morgen", en: "Good morning", es: "Buenos días", emoji: "🌅", lvl: 1 },
      { de: "Guten Abend", en: "Good evening", es: "Buenas tardes", emoji: "🌆", lvl: 2 },
      { de: "Gute Nacht", en: "Good night", es: "Buenas noches", emoji: "🌙", lvl: 1 },
      { de: "Danke", en: "Thank you", es: "Gracias", emoji: "🙏", lvl: 1 },
      { de: "Bitte", en: "Please", es: "Por favor", emoji: "🥺", lvl: 1 },
      { de: "Gern geschehen", en: "You're welcome", es: "De nada", emoji: "😊", lvl: 2 },
      { de: "Ja", en: "Yes", es: "Sí", emoji: "✅", lvl: 1 },
      { de: "Nein", en: "No", es: "No", emoji: "❌", lvl: 1 },
      { de: "Vielleicht", en: "Maybe", es: "Quizás", emoji: "🤷", lvl: 2 },
      { de: "Entschuldigung", en: "Sorry", es: "Perdón", emoji: "🙇", lvl: 1 },
      { de: "Wie geht's?", en: "How are you?", es: "¿Qué tal?", emoji: "🤗", lvl: 1 },
      { de: "Mir geht es gut", en: "I'm fine", es: "Estoy bien", emoji: "😄", lvl: 2 },
      { de: "Ich heiße ...", en: "My name is ...", es: "Me llamo ...", emoji: "📛", lvl: 1 },
      { de: "Wie heißt du?", en: "What's your name?", es: "¿Cómo te llamas?", emoji: "❓", lvl: 1 },
      { de: "Wo ist ...?", en: "Where is ...?", es: "¿Dónde está ...?", emoji: "🧭", lvl: 2 },
      { de: "Wie viel kostet das?", en: "How much is it?", es: "¿Cuánto cuesta?", emoji: "💶", lvl: 2 },
      { de: "Ich verstehe nicht", en: "I don't understand", es: "No entiendo", emoji: "😕", lvl: 2 },
      { de: "Hilfe!", en: "Help!", es: "¡Socorro!", emoji: "🆘", lvl: 1 },
      { de: "Willkommen", en: "Welcome", es: "Bienvenido", emoji: "🎉", lvl: 1 },
      { de: "Viel Glück", en: "Good luck", es: "Buena suerte", emoji: "🍀", lvl: 1 },
      { de: "Herzlichen Glückwunsch", en: "Congratulations", es: "Felicidades", emoji: "🥳", lvl: 2 },
      { de: "Guten Appetit", en: "Enjoy your meal", es: "¡Buen provecho!", emoji: "🍽️", lvl: 1 },
      { de: "Prost", en: "Cheers", es: "Salud", emoji: "🥂", lvl: 2 },
      { de: "Bis morgen", en: "See you tomorrow", es: "Hasta mañana", emoji: "📅", lvl: 2 },
      { de: "Bis bald", en: "See you soon", es: "Hasta pronto", emoji: "🔜", lvl: 1 },
      { de: "Ich liebe dich", en: "I love you", es: "Te quiero", emoji: "❤️", lvl: 1 },
    ],
  },
];

export const ALL_WORDS_COUNT = CATEGORIES.reduce((n, c) => n + c.words.length, 0);

export function categoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
