import { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "tiere",
    name: "Tiere",
    emoji: "🐶",
    from: "#f7b733",
    to: "#fc4a1a",
    words: [
      { de: "der Hund", en: "dog", es: "el perro", emoji: "🐶", lvl: 1 },
      { de: "die Katze", en: "cat", es: "el gato", emoji: "🐱", lvl: 1 },
      { de: "die Maus", en: "mouse", es: "el ratón", emoji: "🐭", lvl: 1 },
      { de: "das Pferd", en: "horse", es: "el caballo", emoji: "🐴", lvl: 1 },
      { de: "die Kuh", en: "cow", es: "la vaca", emoji: "🐮", lvl: 1 },
      { de: "das Schwein", en: "pig", es: "el cerdo", emoji: "🐷", lvl: 1 },
      { de: "das Schaf", en: "sheep", es: "la oveja", emoji: "🐑", lvl: 2 },
      { de: "die Ziege", en: "goat", es: "la cabra", emoji: "🐐", lvl: 2 },
      { de: "das Huhn", en: "chicken", es: "la gallina", emoji: "🐔", lvl: 1 },
      { de: "die Ente", en: "duck", es: "el pato", emoji: "🦆", lvl: 1 },
      { de: "der Vogel", en: "bird", es: "el pájaro", emoji: "🐦", lvl: 1 },
      { de: "der Fisch", en: "fish", es: "el pez", emoji: "🐟", lvl: 1 },
      { de: "der Löwe", en: "lion", es: "el león", emoji: "🦁", lvl: 1 },
      { de: "der Tiger", en: "tiger", es: "el tigre", emoji: "🐯", lvl: 1 },
      { de: "der Elefant", en: "elephant", es: "el elefante", emoji: "🐘", lvl: 1 },
      { de: "der Affe", en: "monkey", es: "el mono", emoji: "🐵", lvl: 1 },
      { de: "der Bär", en: "bear", es: "el oso", emoji: "🐻", lvl: 1 },
      { de: "der Wolf", en: "wolf", es: "el lobo", emoji: "🐺", lvl: 2 },
      { de: "der Fuchs", en: "fox", es: "el zorro", emoji: "🦊", lvl: 2 },
      { de: "der Hase", en: "rabbit", es: "el conejo", emoji: "🐰", lvl: 1 },
      { de: "der Frosch", en: "frog", es: "la rana", emoji: "🐸", lvl: 1 },
      { de: "die Schlange", en: "snake", es: "la serpiente", emoji: "🐍", lvl: 2 },
      { de: "die Spinne", en: "spider", es: "la araña", emoji: "🕷️", lvl: 2 },
      { de: "die Biene", en: "bee", es: "la abeja", emoji: "🐝", lvl: 2 },
      { de: "der Schmetterling", en: "butterfly", es: "la mariposa", emoji: "🦋", lvl: 2 },
      { de: "die Ameise", en: "ant", es: "la hormiga", emoji: "🐜", lvl: 3 },
      { de: "die Giraffe", en: "giraffe", es: "la jirafa", emoji: "🦒", lvl: 1 },
      { de: "das Zebra", en: "zebra", es: "la cebra", emoji: "🦓", lvl: 2 },
      { de: "das Känguru", en: "kangaroo", es: "el canguro", emoji: "🦘", lvl: 2 },
      { de: "der Pinguin", en: "penguin", es: "el pingüino", emoji: "🐧", lvl: 1 },
      { de: "die Eule", en: "owl", es: "el búho", emoji: "🦉", lvl: 2 },
      { de: "der Delfin", en: "dolphin", es: "el delfín", emoji: "🐬", lvl: 2 },
      { de: "der Wal", en: "whale", es: "la ballena", emoji: "🐳", lvl: 2 },
      { de: "der Hai", en: "shark", es: "el tiburón", emoji: "🦈", lvl: 2 },
      { de: "das Krokodil", en: "crocodile", es: "el cocodrilo", emoji: "🐊", lvl: 2 },
      { de: "die Schildkröte", en: "turtle", es: "la tortuga", emoji: "🐢", lvl: 2 },
      { de: "der Igel", en: "hedgehog", es: "el erizo", emoji: "🦔", lvl: 3 },
      { de: "das Eichhörnchen", en: "squirrel", es: "la ardilla", emoji: "🐿️", lvl: 3 },
      { de: "der Adler", en: "eagle", es: "el águila", emoji: "🦅", lvl: 3 },
      { de: "der Krebs", en: "crab", es: "el cangrejo", emoji: "🦀", lvl: 3 },
    ],
  },
  {
    id: "essen",
    name: "Essen & Trinken",
    emoji: "🍎",
    from: "#ff758c",
    to: "#ff7eb3",
    words: [
      { de: "der Apfel", en: "apple", es: "la manzana", emoji: "🍎", lvl: 1 },
      { de: "die Banane", en: "banana", es: "el plátano", emoji: "🍌", lvl: 1 },
      { de: "die Orange", en: "orange", es: "la naranja", emoji: "🍊", lvl: 1 },
      { de: "die Erdbeere", en: "strawberry", es: "la fresa", emoji: "🍓", lvl: 1 },
      { de: "die Zitrone", en: "lemon", es: "el limón", emoji: "🍋", lvl: 2 },
      { de: "die Kirsche", en: "cherry", es: "la cereza", emoji: "🍒", lvl: 2 },
      { de: "die Traube", en: "grape", es: "la uva", emoji: "🍇", lvl: 2 },
      { de: "die Wassermelone", en: "watermelon", es: "la sandía", emoji: "🍉", lvl: 2 },
      { de: "die Birne", en: "pear", es: "la pera", emoji: "🍐", lvl: 2 },
      { de: "der Pfirsich", en: "peach", es: "el melocotón", emoji: "🍑", lvl: 3 },
      { de: "die Ananas", en: "pineapple", es: "la piña", emoji: "🍍", lvl: 2 },
      { de: "die Tomate", en: "tomato", es: "el tomate", emoji: "🍅", lvl: 1 },
      { de: "die Kartoffel", en: "potato", es: "la patata", emoji: "🥔", lvl: 1 },
      { de: "die Karotte", en: "carrot", es: "la zanahoria", emoji: "🥕", lvl: 1 },
      { de: "die Zwiebel", en: "onion", es: "la cebolla", emoji: "🧅", lvl: 3 },
      { de: "der Salat", en: "salad", es: "la ensalada", emoji: "🥗", lvl: 2 },
      { de: "das Brot", en: "bread", es: "el pan", emoji: "🍞", lvl: 1 },
      { de: "der Käse", en: "cheese", es: "el queso", emoji: "🧀", lvl: 1 },
      { de: "das Ei", en: "egg", es: "el huevo", emoji: "🥚", lvl: 1 },
      { de: "die Milch", en: "milk", es: "la leche", emoji: "🥛", lvl: 1 },
      { de: "die Butter", en: "butter", es: "la mantequilla", emoji: "🧈", lvl: 2 },
      { de: "der Reis", en: "rice", es: "el arroz", emoji: "🍚", lvl: 2 },
      { de: "die Nudeln", en: "pasta", es: "la pasta", emoji: "🍝", lvl: 1 },
      { de: "die Pizza", en: "pizza", es: "la pizza", emoji: "🍕", lvl: 1 },
      { de: "die Suppe", en: "soup", es: "la sopa", emoji: "🍲", lvl: 2 },
      { de: "das Fleisch", en: "meat", es: "la carne", emoji: "🥩", lvl: 2 },
      { de: "das Hähnchen", en: "chicken", es: "el pollo", emoji: "🍗", lvl: 2 },
      { de: "der Schinken", en: "ham", es: "el jamón", emoji: "🥓", lvl: 3 },
      { de: "der Honig", en: "honey", es: "la miel", emoji: "🍯", lvl: 3 },
      { de: "der Zucker", en: "sugar", es: "el azúcar", emoji: "🥄", lvl: 3 },
      { de: "das Salz", en: "salt", es: "la sal", emoji: "🧂", lvl: 2 },
      { de: "der Kuchen", en: "cake", es: "el pastel", emoji: "🍰", lvl: 1 },
      { de: "der Keks", en: "cookie", es: "la galleta", emoji: "🍪", lvl: 1 },
      { de: "die Schokolade", en: "chocolate", es: "el chocolate", emoji: "🍫", lvl: 1 },
      { de: "das Eis", en: "ice cream", es: "el helado", emoji: "🍦", lvl: 1 },
      { de: "das Bonbon", en: "candy", es: "el caramelo", emoji: "🍬", lvl: 2 },
      { de: "das Wasser", en: "water", es: "el agua", emoji: "💧", lvl: 1 },
      { de: "der Saft", en: "juice", es: "el zumo", emoji: "🧃", lvl: 1 },
      { de: "der Tee", en: "tea", es: "el té", emoji: "🍵", lvl: 2 },
      { de: "der Kaffee", en: "coffee", es: "el café", emoji: "☕", lvl: 1 },
    ],
  },
  {
    id: "familie",
    name: "Familie & Menschen",
    emoji: "👨‍👩‍👧",
    from: "#a18cd1",
    to: "#fbc2eb",
    words: [
      { de: "die Mutter", en: "mother", es: "la madre", emoji: "👩", lvl: 1 },
      { de: "der Vater", en: "father", es: "el padre", emoji: "👨", lvl: 1 },
      { de: "die Eltern", en: "parents", es: "los padres", emoji: "👫", lvl: 2 },
      { de: "die Schwester", en: "sister", es: "la hermana", emoji: "👧", lvl: 1 },
      { de: "der Bruder", en: "brother", es: "el hermano", emoji: "👦", lvl: 1 },
      { de: "die Oma", en: "grandma", es: "la abuela", emoji: "👵", lvl: 1 },
      { de: "der Opa", en: "grandpa", es: "el abuelo", emoji: "👴", lvl: 1 },
      { de: "die Tante", en: "aunt", es: "la tía", emoji: "💁‍♀️", lvl: 2 },
      { de: "der Onkel", en: "uncle", es: "el tío", emoji: "🙋‍♂️", lvl: 2 },
      { de: "der Cousin", en: "cousin", es: "el primo", emoji: "🧑", lvl: 3 },
      { de: "das Baby", en: "baby", es: "el bebé", emoji: "👶", lvl: 1 },
      { de: "das Kind", en: "child", es: "el niño", emoji: "🧒", lvl: 1 },
      { de: "der Junge", en: "boy", es: "el chico", emoji: "👦", lvl: 1 },
      { de: "das Mädchen", en: "girl", es: "la chica", emoji: "👧", lvl: 1 },
      { de: "der Mann", en: "man", es: "el hombre", emoji: "🧔", lvl: 1 },
      { de: "die Frau", en: "woman", es: "la mujer", emoji: "👱‍♀️", lvl: 1 },
      { de: "der Sohn", en: "son", es: "el hijo", emoji: "👨‍👦", lvl: 2 },
      { de: "die Tochter", en: "daughter", es: "la hija", emoji: "👩‍👧", lvl: 2 },
      { de: "die Familie", en: "family", es: "la familia", emoji: "👨‍👩‍👧‍👦", lvl: 1 },
      { de: "der Freund", en: "friend", es: "el amigo", emoji: "🤝", lvl: 1 },
      { de: "die Freundin", en: "friend (girl)", es: "la amiga", emoji: "👭", lvl: 2 },
      { de: "der Nachbar", en: "neighbour", es: "el vecino", emoji: "🏘️", lvl: 3 },
      { de: "der Lehrer", en: "teacher", es: "el profesor", emoji: "🧑‍🏫", lvl: 1 },
      { de: "der Arzt", en: "doctor", es: "el médico", emoji: "🧑‍⚕️", lvl: 2 },
      { de: "der Polizist", en: "police officer", es: "el policía", emoji: "👮", lvl: 2 },
      { de: "der Feuerwehrmann", en: "firefighter", es: "el bombero", emoji: "🧑‍🚒", lvl: 2 },
      { de: "der Koch", en: "cook", es: "el cocinero", emoji: "🧑‍🍳", lvl: 2 },
      { de: "der Bauer", en: "farmer", es: "el agricultor", emoji: "🧑‍🌾", lvl: 3 },
      { de: "die Zwillinge", en: "twins", es: "los gemelos", emoji: "👯", lvl: 3 },
      { de: "der Ehemann", en: "husband", es: "el marido", emoji: "🤵", lvl: 3 },
      { de: "die Ehefrau", en: "wife", es: "la esposa", emoji: "👰", lvl: 3 },
      { de: "die Person", en: "person", es: "la persona", emoji: "🧍", lvl: 2 },
      { de: "die Leute", en: "people", es: "la gente", emoji: "👥", lvl: 2 },
      { de: "der Name", en: "name", es: "el nombre", emoji: "📛", lvl: 2 },
      { de: "der Geburtstag", en: "birthday", es: "el cumpleaños", emoji: "🎂", lvl: 1 },
      { de: "der Gast", en: "guest", es: "el invitado", emoji: "🛎️", lvl: 3 },
    ],
  },
  {
    id: "farben",
    name: "Farben & Formen",
    emoji: "🎨",
    from: "#ff6ec4",
    to: "#7873f5",
    words: [
      { de: "rot", en: "red", es: "rojo", emoji: "🔴", lvl: 1 },
      { de: "blau", en: "blue", es: "azul", emoji: "🔵", lvl: 1 },
      { de: "grün", en: "green", es: "verde", emoji: "🟢", lvl: 1 },
      { de: "gelb", en: "yellow", es: "amarillo", emoji: "🟡", lvl: 1 },
      { de: "orange", en: "orange", es: "naranja", emoji: "🟠", lvl: 1 },
      { de: "lila", en: "purple", es: "morado", emoji: "🟣", lvl: 1 },
      { de: "rosa", en: "pink", es: "rosa", emoji: "🌸", lvl: 1 },
      { de: "braun", en: "brown", es: "marrón", emoji: "🟤", lvl: 1 },
      { de: "schwarz", en: "black", es: "negro", emoji: "⚫", lvl: 1 },
      { de: "weiß", en: "white", es: "blanco", emoji: "⚪", lvl: 1 },
      { de: "grau", en: "grey", es: "gris", emoji: "🩶", lvl: 2 },
      { de: "golden", en: "golden", es: "dorado", emoji: "🥇", lvl: 2 },
      { de: "silbern", en: "silver", es: "plateado", emoji: "🥈", lvl: 2 },
      { de: "hell", en: "light", es: "claro", emoji: "💡", lvl: 2 },
      { de: "dunkel", en: "dark", es: "oscuro", emoji: "🌑", lvl: 2 },
      { de: "bunt", en: "colourful", es: "de colores", emoji: "🌈", lvl: 2 },
      { de: "der Kreis", en: "circle", es: "el círculo", emoji: "⭕", lvl: 2 },
      { de: "das Quadrat", en: "square", es: "el cuadrado", emoji: "🟥", lvl: 2 },
      { de: "das Dreieck", en: "triangle", es: "el triángulo", emoji: "🔺", lvl: 2 },
      { de: "das Rechteck", en: "rectangle", es: "el rectángulo", emoji: "🟦", lvl: 3 },
      { de: "der Stern", en: "star", es: "la estrella", emoji: "⭐", lvl: 1 },
      { de: "das Herz", en: "heart", es: "el corazón", emoji: "❤️", lvl: 1 },
      { de: "der Punkt", en: "dot", es: "el punto", emoji: "🔘", lvl: 3 },
      { de: "die Linie", en: "line", es: "la línea", emoji: "〰️", lvl: 3 },
      { de: "der Pfeil", en: "arrow", es: "la flecha", emoji: "➡️", lvl: 2 },
      { de: "die Form", en: "shape", es: "la forma", emoji: "🔷", lvl: 3 },
      { de: "der Würfel", en: "cube", es: "el cubo", emoji: "🎲", lvl: 3 },
      { de: "das Muster", en: "pattern", es: "el patrón", emoji: "🧩", lvl: 3 },
    ],
  },
  {
    id: "zahlen",
    name: "Zahlen",
    emoji: "🔢",
    from: "#4facfe",
    to: "#00f2fe",
    words: [
      { de: "null", en: "zero", es: "cero", emoji: "0️⃣", lvl: 1 },
      { de: "eins", en: "one", es: "uno", emoji: "1️⃣", lvl: 1 },
      { de: "zwei", en: "two", es: "dos", emoji: "2️⃣", lvl: 1 },
      { de: "drei", en: "three", es: "tres", emoji: "3️⃣", lvl: 1 },
      { de: "vier", en: "four", es: "cuatro", emoji: "4️⃣", lvl: 1 },
      { de: "fünf", en: "five", es: "cinco", emoji: "5️⃣", lvl: 1 },
      { de: "sechs", en: "six", es: "seis", emoji: "6️⃣", lvl: 1 },
      { de: "sieben", en: "seven", es: "siete", emoji: "7️⃣", lvl: 1 },
      { de: "acht", en: "eight", es: "ocho", emoji: "8️⃣", lvl: 1 },
      { de: "neun", en: "nine", es: "nueve", emoji: "9️⃣", lvl: 1 },
      { de: "zehn", en: "ten", es: "diez", emoji: "🔟", lvl: 1 },
      { de: "elf", en: "eleven", es: "once", emoji: "1️⃣1️⃣", lvl: 2 },
      { de: "zwölf", en: "twelve", es: "doce", emoji: "1️⃣2️⃣", lvl: 2 },
      { de: "dreizehn", en: "thirteen", es: "trece", emoji: "1️⃣3️⃣", lvl: 2 },
      { de: "vierzehn", en: "fourteen", es: "catorce", emoji: "1️⃣4️⃣", lvl: 2 },
      { de: "fünfzehn", en: "fifteen", es: "quince", emoji: "1️⃣5️⃣", lvl: 2 },
      { de: "sechzehn", en: "sixteen", es: "dieciséis", emoji: "1️⃣6️⃣", lvl: 2 },
      { de: "siebzehn", en: "seventeen", es: "diecisiete", emoji: "1️⃣7️⃣", lvl: 2 },
      { de: "achtzehn", en: "eighteen", es: "dieciocho", emoji: "1️⃣8️⃣", lvl: 2 },
      { de: "neunzehn", en: "nineteen", es: "diecinueve", emoji: "1️⃣9️⃣", lvl: 2 },
      { de: "zwanzig", en: "twenty", es: "veinte", emoji: "2️⃣0️⃣", lvl: 2 },
      { de: "dreißig", en: "thirty", es: "treinta", emoji: "3️⃣0️⃣", lvl: 3 },
      { de: "vierzig", en: "forty", es: "cuarenta", emoji: "4️⃣0️⃣", lvl: 3 },
      { de: "fünfzig", en: "fifty", es: "cincuenta", emoji: "5️⃣0️⃣", lvl: 3 },
      { de: "sechzig", en: "sixty", es: "sesenta", emoji: "6️⃣0️⃣", lvl: 3 },
      { de: "siebzig", en: "seventy", es: "setenta", emoji: "7️⃣0️⃣", lvl: 3 },
      { de: "achtzig", en: "eighty", es: "ochenta", emoji: "8️⃣0️⃣", lvl: 3 },
      { de: "neunzig", en: "ninety", es: "noventa", emoji: "9️⃣0️⃣", lvl: 3 },
      { de: "hundert", en: "one hundred", es: "cien", emoji: "💯", lvl: 2 },
      { de: "tausend", en: "one thousand", es: "mil", emoji: "🔢", lvl: 3 },
      { de: "die Hälfte", en: "half", es: "la mitad", emoji: "➗", lvl: 3 },
    ],
  },
  {
    id: "koerper",
    name: "Körper",
    emoji: "💪",
    from: "#fa709a",
    to: "#fee140",
    words: [
      { de: "der Kopf", en: "head", es: "la cabeza", emoji: "👤", lvl: 1 },
      { de: "das Haar", en: "hair", es: "el pelo", emoji: "💇", lvl: 1 },
      { de: "das Gesicht", en: "face", es: "la cara", emoji: "🙂", lvl: 1 },
      { de: "das Auge", en: "eye", es: "el ojo", emoji: "👁️", lvl: 1 },
      { de: "das Ohr", en: "ear", es: "la oreja", emoji: "👂", lvl: 1 },
      { de: "die Nase", en: "nose", es: "la nariz", emoji: "👃", lvl: 1 },
      { de: "der Mund", en: "mouth", es: "la boca", emoji: "👄", lvl: 1 },
      { de: "der Zahn", en: "tooth", es: "el diente", emoji: "🦷", lvl: 1 },
      { de: "die Zunge", en: "tongue", es: "la lengua", emoji: "👅", lvl: 2 },
      { de: "die Lippe", en: "lip", es: "el labio", emoji: "💋", lvl: 3 },
      { de: "der Hals", en: "neck", es: "el cuello", emoji: "🦒", lvl: 2 },
      { de: "die Schulter", en: "shoulder", es: "el hombro", emoji: "🤷", lvl: 2 },
      { de: "der Arm", en: "arm", es: "el brazo", emoji: "💪", lvl: 1 },
      { de: "der Ellbogen", en: "elbow", es: "el codo", emoji: "🦾", lvl: 3 },
      { de: "die Hand", en: "hand", es: "la mano", emoji: "✋", lvl: 1 },
      { de: "der Finger", en: "finger", es: "el dedo", emoji: "☝️", lvl: 1 },
      { de: "der Daumen", en: "thumb", es: "el pulgar", emoji: "👍", lvl: 2 },
      { de: "der Bauch", en: "belly", es: "la barriga", emoji: "🤰", lvl: 2 },
      { de: "der Rücken", en: "back", es: "la espalda", emoji: "🔙", lvl: 2 },
      { de: "das Bein", en: "leg", es: "la pierna", emoji: "🦵", lvl: 1 },
      { de: "das Knie", en: "knee", es: "la rodilla", emoji: "🧎", lvl: 2 },
      { de: "der Fuß", en: "foot", es: "el pie", emoji: "🦶", lvl: 1 },
      { de: "der Zeh", en: "toe", es: "el dedo del pie", emoji: "🩴", lvl: 3 },
      { de: "das Blut", en: "blood", es: "la sangre", emoji: "🩸", lvl: 3 },
      { de: "der Knochen", en: "bone", es: "el hueso", emoji: "🦴", lvl: 2 },
      { de: "die Haut", en: "skin", es: "la piel", emoji: "🧴", lvl: 3 },
      { de: "das Gehirn", en: "brain", es: "el cerebro", emoji: "🧠", lvl: 2 },
      { de: "der Muskel", en: "muscle", es: "el músculo", emoji: "🏋️", lvl: 3 },
      { de: "die Augenbraue", en: "eyebrow", es: "la ceja", emoji: "🤨", lvl: 3 },
      { de: "die Wange", en: "cheek", es: "la mejilla", emoji: "☺️", lvl: 3 },
      { de: "das Kinn", en: "chin", es: "la barbilla", emoji: "😶", lvl: 3 },
      { de: "der Fingernagel", en: "fingernail", es: "la uña", emoji: "💅", lvl: 3 },
      { de: "der Bart", en: "beard", es: "la barba", emoji: "🧔", lvl: 2 },
      { de: "der Körper", en: "body", es: "el cuerpo", emoji: "🧍", lvl: 1 },
      { de: "das Skelett", en: "skeleton", es: "el esqueleto", emoji: "💀", lvl: 2 },
    ],
  },
  {
    id: "kleidung",
    name: "Kleidung",
    emoji: "👕",
    from: "#5ee7df",
    to: "#b490ca",
    words: [
      { de: "das T-Shirt", en: "t-shirt", es: "la camiseta", emoji: "👕", lvl: 1 },
      { de: "die Hose", en: "trousers", es: "los pantalones", emoji: "👖", lvl: 1 },
      { de: "das Kleid", en: "dress", es: "el vestido", emoji: "👗", lvl: 1 },
      { de: "der Rock", en: "skirt", es: "la falda", emoji: "💃", lvl: 2 },
      { de: "der Pullover", en: "sweater", es: "el jersey", emoji: "🧶", lvl: 2 },
      { de: "die Jacke", en: "jacket", es: "la chaqueta", emoji: "🧥", lvl: 1 },
      { de: "der Mantel", en: "coat", es: "el abrigo", emoji: "🥼", lvl: 2 },
      { de: "der Schuh", en: "shoe", es: "el zapato", emoji: "👟", lvl: 1 },
      { de: "der Stiefel", en: "boot", es: "la bota", emoji: "👢", lvl: 2 },
      { de: "die Socke", en: "sock", es: "el calcetín", emoji: "🧦", lvl: 1 },
      { de: "der Hut", en: "hat", es: "el sombrero", emoji: "🎩", lvl: 1 },
      { de: "die Mütze", en: "cap", es: "la gorra", emoji: "🧢", lvl: 1 },
      { de: "der Schal", en: "scarf", es: "la bufanda", emoji: "🧣", lvl: 2 },
      { de: "der Handschuh", en: "glove", es: "el guante", emoji: "🧤", lvl: 2 },
      { de: "der Gürtel", en: "belt", es: "el cinturón", emoji: "➰", lvl: 3 },
      { de: "die Krawatte", en: "tie", es: "la corbata", emoji: "👔", lvl: 3 },
      { de: "der Anzug", en: "suit", es: "el traje", emoji: "🤵", lvl: 3 },
      { de: "der Schlafanzug", en: "pyjamas", es: "el pijama", emoji: "🛌", lvl: 2 },
      { de: "der Badeanzug", en: "swimsuit", es: "el bañador", emoji: "🩱", lvl: 2 },
      { de: "die Unterhose", en: "underpants", es: "los calzoncillos", emoji: "🩲", lvl: 2 },
      { de: "die Brille", en: "glasses", es: "las gafas", emoji: "👓", lvl: 1 },
      { de: "die Sonnenbrille", en: "sunglasses", es: "las gafas de sol", emoji: "🕶️", lvl: 2 },
      { de: "die Uhr", en: "watch", es: "el reloj", emoji: "⌚", lvl: 1 },
      { de: "der Ring", en: "ring", es: "el anillo", emoji: "💍", lvl: 2 },
      { de: "die Halskette", en: "necklace", es: "el collar", emoji: "📿", lvl: 3 },
      { de: "die Tasche", en: "bag", es: "el bolso", emoji: "👜", lvl: 2 },
      { de: "der Rucksack", en: "backpack", es: "la mochila", emoji: "🎒", lvl: 1 },
      { de: "der Regenschirm", en: "umbrella", es: "el paraguas", emoji: "☂️", lvl: 2 },
      { de: "der Knopf", en: "button", es: "el botón", emoji: "🔘", lvl: 3 },
      { de: "der Reißverschluss", en: "zip", es: "la cremallera", emoji: "🤐", lvl: 3 },
      { de: "die Sandale", en: "sandal", es: "la sandalia", emoji: "🩴", lvl: 2 },
      { de: "die Shorts", en: "shorts", es: "los pantalones cortos", emoji: "🩳", lvl: 2 },
    ],
  },
  {
    id: "schule",
    name: "Schule",
    emoji: "🏫",
    from: "#667eea",
    to: "#764ba2",
    words: [
      { de: "die Schule", en: "school", es: "la escuela", emoji: "🏫", lvl: 1 },
      { de: "die Klasse", en: "class", es: "la clase", emoji: "👩‍🏫", lvl: 2 },
      { de: "der Schüler", en: "pupil", es: "el alumno", emoji: "🧑‍🎓", lvl: 2 },
      { de: "das Buch", en: "book", es: "el libro", emoji: "📖", lvl: 1 },
      { de: "das Heft", en: "notebook", es: "el cuaderno", emoji: "📓", lvl: 1 },
      { de: "der Stift", en: "pen", es: "el bolígrafo", emoji: "🖊️", lvl: 1 },
      { de: "der Bleistift", en: "pencil", es: "el lápiz", emoji: "✏️", lvl: 1 },
      { de: "der Radiergummi", en: "rubber", es: "la goma", emoji: "🧽", lvl: 2 },
      { de: "das Lineal", en: "ruler", es: "la regla", emoji: "📏", lvl: 2 },
      { de: "die Schere", en: "scissors", es: "las tijeras", emoji: "✂️", lvl: 1 },
      { de: "der Kleber", en: "glue", es: "el pegamento", emoji: "🩹", lvl: 2 },
      { de: "die Tafel", en: "blackboard", es: "la pizarra", emoji: "⬛", lvl: 2 },
      { de: "die Kreide", en: "chalk", es: "la tiza", emoji: "🖍️", lvl: 3 },
      { de: "der Stuhl", en: "chair", es: "la silla", emoji: "🪑", lvl: 1 },
      { de: "der Tisch", en: "table", es: "la mesa", emoji: "🍽️", lvl: 1 },
      { de: "die Pause", en: "break", es: "el recreo", emoji: "⏰", lvl: 1 },
      { de: "die Hausaufgaben", en: "homework", es: "los deberes", emoji: "📝", lvl: 1 },
      { de: "die Prüfung", en: "exam", es: "el examen", emoji: "📄", lvl: 2 },
      { de: "die Frage", en: "question", es: "la pregunta", emoji: "❓", lvl: 1 },
      { de: "die Antwort", en: "answer", es: "la respuesta", emoji: "✅", lvl: 1 },
      { de: "lesen", en: "to read", es: "leer", emoji: "📚", lvl: 1 },
      { de: "schreiben", en: "to write", es: "escribir", emoji: "✍️", lvl: 1 },
      { de: "rechnen", en: "to do maths", es: "calcular", emoji: "🧮", lvl: 2 },
      { de: "malen", en: "to paint", es: "pintar", emoji: "🎨", lvl: 1 },
      { de: "lernen", en: "to learn", es: "aprender", emoji: "🎓", lvl: 1 },
      { de: "sprechen", en: "to speak", es: "hablar", emoji: "🗣️", lvl: 1 },
      { de: "hören", en: "to listen", es: "escuchar", emoji: "🎧", lvl: 1 },
      { de: "verstehen", en: "to understand", es: "entender", emoji: "💡", lvl: 2 },
      { de: "Mathe", en: "maths", es: "las matemáticas", emoji: "➕", lvl: 1 },
      { de: "die Musik", en: "music", es: "la música", emoji: "🎵", lvl: 1 },
      { de: "die Kunst", en: "art", es: "el arte", emoji: "🖼️", lvl: 2 },
      { de: "der Computer", en: "computer", es: "el ordenador", emoji: "💻", lvl: 1 },
      { de: "das Papier", en: "paper", es: "el papel", emoji: "📃", lvl: 1 },
      { de: "das Wort", en: "word", es: "la palabra", emoji: "🔤", lvl: 1 },
      { de: "der Satz", en: "sentence", es: "la frase", emoji: "💬", lvl: 2 },
      { de: "die Sprache", en: "language", es: "el idioma", emoji: "🌐", lvl: 2 },
      { de: "Englisch", en: "English", es: "el inglés", emoji: "🇬🇧", lvl: 1 },
      { de: "Spanisch", en: "Spanish", es: "el español", emoji: "🇪🇸", lvl: 1 },
      { de: "Deutsch", en: "German", es: "el alemán", emoji: "🇩🇪", lvl: 1 },
      { de: "die Ferien", en: "holidays", es: "las vacaciones", emoji: "🏖️", lvl: 1 },
    ],
  },
  {
    id: "natur",
    name: "Natur & Wetter",
    emoji: "🌳",
    from: "#0ba360",
    to: "#3cba92",
    words: [
      { de: "die Sonne", en: "sun", es: "el sol", emoji: "☀️", lvl: 1 },
      { de: "der Mond", en: "moon", es: "la luna", emoji: "🌙", lvl: 1 },
      { de: "der Himmel", en: "sky", es: "el cielo", emoji: "🌌", lvl: 1 },
      { de: "die Wolke", en: "cloud", es: "la nube", emoji: "☁️", lvl: 1 },
      { de: "der Regen", en: "rain", es: "la lluvia", emoji: "🌧️", lvl: 1 },
      { de: "der Schnee", en: "snow", es: "la nieve", emoji: "❄️", lvl: 1 },
      { de: "der Wind", en: "wind", es: "el viento", emoji: "💨", lvl: 1 },
      { de: "der Sturm", en: "storm", es: "la tormenta", emoji: "⛈️", lvl: 2 },
      { de: "der Blitz", en: "lightning", es: "el rayo", emoji: "⚡", lvl: 2 },
      { de: "der Regenbogen", en: "rainbow", es: "el arco iris", emoji: "🌈", lvl: 1 },
      { de: "der Nebel", en: "fog", es: "la niebla", emoji: "🌫️", lvl: 3 },
      { de: "das Eis", en: "ice", es: "el hielo", emoji: "🧊", lvl: 2 },
      { de: "der Baum", en: "tree", es: "el árbol", emoji: "🌳", lvl: 1 },
      { de: "die Blume", en: "flower", es: "la flor", emoji: "🌼", lvl: 1 },
      { de: "das Gras", en: "grass", es: "la hierba", emoji: "🌱", lvl: 1 },
      { de: "das Blatt", en: "leaf", es: "la hoja", emoji: "🍃", lvl: 2 },
      { de: "der Wald", en: "forest", es: "el bosque", emoji: "🌲", lvl: 1 },
      { de: "der Berg", en: "mountain", es: "la montaña", emoji: "⛰️", lvl: 1 },
      { de: "der Fluss", en: "river", es: "el río", emoji: "🏞️", lvl: 2 },
      { de: "der See", en: "lake", es: "el lago", emoji: "🛶", lvl: 2 },
      { de: "das Meer", en: "sea", es: "el mar", emoji: "🌊", lvl: 1 },
      { de: "der Strand", en: "beach", es: "la playa", emoji: "🏖️", lvl: 1 },
      { de: "die Insel", en: "island", es: "la isla", emoji: "🏝️", lvl: 2 },
      { de: "die Wüste", en: "desert", es: "el desierto", emoji: "🏜️", lvl: 3 },
      { de: "der Stein", en: "stone", es: "la piedra", emoji: "🪨", lvl: 2 },
      { de: "der Sand", en: "sand", es: "la arena", emoji: "⏳", lvl: 2 },
      { de: "das Feuer", en: "fire", es: "el fuego", emoji: "🔥", lvl: 1 },
      { de: "die Erde", en: "earth", es: "la tierra", emoji: "🌍", lvl: 1 },
      { de: "die Natur", en: "nature", es: "la naturaleza", emoji: "🌿", lvl: 2 },
      { de: "das Wetter", en: "weather", es: "el tiempo", emoji: "🌦️", lvl: 1 },
      { de: "heiß", en: "hot", es: "caliente", emoji: "🥵", lvl: 1 },
      { de: "kalt", en: "cold", es: "frío", emoji: "🥶", lvl: 1 },
      { de: "der Frühling", en: "spring", es: "la primavera", emoji: "🌷", lvl: 2 },
      { de: "der Sommer", en: "summer", es: "el verano", emoji: "😎", lvl: 1 },
      { de: "der Herbst", en: "autumn", es: "el otoño", emoji: "🍂", lvl: 2 },
      { de: "der Winter", en: "winter", es: "el invierno", emoji: "⛄", lvl: 1 },
      { de: "die Pflanze", en: "plant", es: "la planta", emoji: "🪴", lvl: 2 },
    ],
  },
  {
    id: "fahrzeuge",
    name: "Fahrzeuge & Verkehr",
    emoji: "🚗",
    from: "#f83600",
    to: "#f9d423",
    words: [
      { de: "das Auto", en: "car", es: "el coche", emoji: "🚗", lvl: 1 },
      { de: "der Bus", en: "bus", es: "el autobús", emoji: "🚌", lvl: 1 },
      { de: "der Zug", en: "train", es: "el tren", emoji: "🚆", lvl: 1 },
      { de: "das Fahrrad", en: "bicycle", es: "la bicicleta", emoji: "🚲", lvl: 1 },
      { de: "das Motorrad", en: "motorbike", es: "la moto", emoji: "🏍️", lvl: 2 },
      { de: "der Lastwagen", en: "lorry", es: "el camión", emoji: "🚚", lvl: 2 },
      { de: "das Flugzeug", en: "plane", es: "el avión", emoji: "✈️", lvl: 1 },
      { de: "der Hubschrauber", en: "helicopter", es: "el helicóptero", emoji: "🚁", lvl: 2 },
      { de: "das Schiff", en: "ship", es: "el barco", emoji: "🚢", lvl: 1 },
      { de: "das Boot", en: "boat", es: "el bote", emoji: "⛵", lvl: 1 },
      { de: "die U-Bahn", en: "underground", es: "el metro", emoji: "🚇", lvl: 2 },
      { de: "die Straßenbahn", en: "tram", es: "el tranvía", emoji: "🚊", lvl: 3 },
      { de: "das Taxi", en: "taxi", es: "el taxi", emoji: "🚕", lvl: 1 },
      { de: "der Krankenwagen", en: "ambulance", es: "la ambulancia", emoji: "🚑", lvl: 2 },
      { de: "das Feuerwehrauto", en: "fire engine", es: "el camión de bomberos", emoji: "🚒", lvl: 1 },
      { de: "das Polizeiauto", en: "police car", es: "el coche de policía", emoji: "🚓", lvl: 1 },
      { de: "der Traktor", en: "tractor", es: "el tractor", emoji: "🚜", lvl: 1 },
      { de: "die Rakete", en: "rocket", es: "el cohete", emoji: "🚀", lvl: 1 },
      { de: "der Heißluftballon", en: "hot-air balloon", es: "el globo", emoji: "🎈", lvl: 2 },
      { de: "der Roller", en: "scooter", es: "el patinete", emoji: "🛴", lvl: 1 },
      { de: "das Skateboard", en: "skateboard", es: "el monopatín", emoji: "🛹", lvl: 2 },
      { de: "die Straße", en: "street", es: "la calle", emoji: "🛣️", lvl: 1 },
      { de: "die Ampel", en: "traffic lights", es: "el semáforo", emoji: "🚦", lvl: 1 },
      { de: "die Brücke", en: "bridge", es: "el puente", emoji: "🌉", lvl: 2 },
      { de: "die Tankstelle", en: "petrol station", es: "la gasolinera", emoji: "⛽", lvl: 3 },
      { de: "der Bahnhof", en: "station", es: "la estación", emoji: "🚉", lvl: 2 },
      { de: "der Flughafen", en: "airport", es: "el aeropuerto", emoji: "🛫", lvl: 2 },
      { de: "der Hafen", en: "port", es: "el puerto", emoji: "⚓", lvl: 3 },
      { de: "das Ticket", en: "ticket", es: "el billete", emoji: "🎫", lvl: 2 },
      { de: "das Rad", en: "wheel", es: "la rueda", emoji: "🛞", lvl: 2 },
      { de: "fahren", en: "to drive", es: "conducir", emoji: "🚙", lvl: 1 },
      { de: "fliegen", en: "to fly", es: "volar", emoji: "🛩️", lvl: 1 },
      { de: "schnell", en: "fast", es: "rápido", emoji: "🏎️", lvl: 1 },
      { de: "langsam", en: "slow", es: "lento", emoji: "🐌", lvl: 1 },
    ],
  },
];

export const ALL_WORDS_COUNT = CATEGORIES.reduce((n, c) => n + c.words.length, 0);

export function categoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
